// Code generated by internal/generate/servicepackage/main.go; DO NOT EDIT.

package inspector

import (
	"context"

	aws_sdkv2 "github.com/aws/aws-sdk-go-v2/aws"
	inspector_sdkv2 "github.com/aws/aws-sdk-go-v2/service/inspector"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*types.ServicePackageFrameworkDataSource {
	return []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
	return []*types.ServicePackageFrameworkResource{}
}

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{
		{
			Factory:  DataSourceRulesPackages,
			TypeName: "aws_inspector_rules_packages",
		},
	}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
			Factory:  ResourceAssessmentTarget,
			TypeName: "aws_inspector_assessment_target",
		},
		{
			Factory:  ResourceAssessmentTemplate,
			TypeName: "aws_inspector_assessment_template",
			Name:     "Assessment Template",
			Tags: &types.ServicePackageResourceTags{
				IdentifierAttribute: names.AttrID,
			},
		},
		{
			Factory:  ResourceResourceGroup,
			TypeName: "aws_inspector_resource_group",
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.Inspector
}

// NewClient returns a new AWS SDK for Go v2 client for this service package's AWS API.
func (p *servicePackage) NewClient(ctx context.Context, config map[string]any) (*inspector_sdkv2.Client, error) {
	cfg := *(config["aws_sdkv2_config"].(*aws_sdkv2.Config))

	return inspector_sdkv2.NewFromConfig(cfg,
		inspector_sdkv2.WithEndpointResolverV2(newEndpointResolverSDKv2()),
		withBaseEndpoint(config[names.AttrEndpoint].(string)),
	), nil
}

func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
