// Code generated by internal/generate/tagstests/main.go; DO NOT EDIT.

package dsql_test

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	tfstatecheck "github.com/hashicorp/terraform-provider-aws/internal/acctest/statecheck"
	tfdsql "github.com/hashicorp/terraform-provider-aws/internal/service/dsql"
)

func expectFullResourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullResourceTags(tfdsql.ServicePackage(context.Background()), resourceAddress, knownValue)
}
