// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

package create

import (
	"context"
	"fmt"
	"math/rand" // nosemgrep: go.lang.security.audit.crypto.math_random.math-random-used -- Deterministic PRNG required for VCR test reproducibility
	"strings"
	"sync"
	"time"

	"github.com/hashicorp/terraform-provider-aws/internal/vcr"
)

const UniqueIdPrefix = `terraform-`

// UniqueIDSuffixLength is the string length of the suffix generated by
// prefixedUniqueId. This can be used by length validation functions to
// ensure prefixes are the correct length for the target field.
const UniqueIDSuffixLength = 26

var (
	idMutex sync.Mutex
	// idCounter is a monotonic counter for generating ordered unique ids.
	idCounter uint32
)

// Helper for a resource to generate a unique identifier with default prefix
//
// This is a VCR-aware variant of the Plugin SDK V2 id.UniqueId function.
// If context contains a VCR randomness source, it uses that for deterministic ID
// generation. Otherwise, it falls back to a time and counter based approach.
func UniqueId(ctx context.Context) string {
	return prefixedUniqueId(ctx, UniqueIdPrefix)
}

// prefixedUniqueId generates a unique ID with the given prefix
//
// This is a VCR-aware variant of the Plugin SDK V2 id.PrefixUniqueId function.
// If context contains a VCR randomness source, it uses that for deterministic ID
// generation. Otherwise, it generates a time and counter based unique ID.
func prefixedUniqueId(ctx context.Context, prefix string) string {
	if s, ok := vcr.FromContext(ctx); ok && s != nil {
		rng := rand.New(s)
		// Pad the generated int64 to match the length of the id.PrefixUniqueId (26 characters)
		return fmt.Sprintf("%s%026x", prefix, rng.Int63())
	}

	// Ported from Terraform Plugin SDK V2
	// https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/id/id.go

	// Be precise to 4 digits of fractional seconds, but remove the dot before the
	// fractional seconds.
	timestamp := strings.Replace(
		time.Now().UTC().Format("20060102150405.0000"), ".", "", 1)

	idMutex.Lock()
	defer idMutex.Unlock()
	idCounter++
	return fmt.Sprintf("%s%s%08x", prefix, timestamp, idCounter)
}
