// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

package create

import (
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	mathrand "math/rand" // nosemgrep: go.lang.security.audit.crypto.math_random.math-random-used -- Deterministic PRNG required for VCR test reproducibility

	"github.com/hashicorp/terraform-provider-aws/internal/errs"
	"github.com/hashicorp/terraform-provider-aws/internal/vcr"
)

const UniqueIDPrefix = `terraform-`

// UniqueIDSuffixLength is the string length of the suffix generated by
// prefixedUniqueID. This can be used by length validation functions to
// ensure prefixes are the correct length for the target field.
const UniqueIDSuffixLength = 26

// Helper for a resource to generate a unique identifier with default prefix
//
// If context contains a VCR randomness source, it uses that for deterministic ID
// generation. Otherwise, it falls back to a cryptographically strong random generator approach.
func UniqueId(ctx context.Context) string {
	return prefixedUniqueID(ctx, UniqueIDPrefix, alphaNum)
}

// prefixedUniqueID generates a unique ID with the given prefix
//
// If context contains a VCR randomness source, it uses that for deterministic ID
// generation. Otherwise, inspired by https://github.com/matoous/go-nanoid.
func prefixedUniqueID(ctx context.Context, prefix, alphabet string) string {
	if s, ok := vcr.FromContext(ctx); ok && s != nil {
		rng := mathrand.New(s)
		// Pad the generated int64 to match the length of the id.PrefixUniqueId (26 characters)
		return fmt.Sprintf("%s%0*x", prefix, UniqueIDSuffixLength, rng.Int63())
	}

	return prefix + errs.Must(generateID(alphabet, UniqueIDSuffixLength))
}

const (
	// alphaNum is an alphabet of alpha-numerical characters.
	alphaNum = `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`

	// hexLower is an alphabet of lowercase hexadecimal digit characters.
	hexLower = "abcdef0123456789"
)

// generateID returns a length-character string drawn uniformly from alphabet.
// alphabet is treated as bytes (ASCII), so it must be 1..256 bytes.
func generateID(alphabet string, length int) (string, error) {
	n := len(alphabet)
	if n == 0 || n > 256 {
		return "", errors.New("alphabet must be 1..256 bytes")
	}
	if length <= 0 {
		return "", errors.New("length must be positive")
	}

	// Largest multiple of n that fits in a byte; values >= this are rejected
	// so the modulo is unbiased.
	limit := 256 - (256 % n)

	id := make([]byte, length)
	buf := make([]byte, length) // read in batches; refill as needed
	i := 0
	for i < length {
		rand.Read(buf) //nolint:errcheck // crypto/rand.Read returns nil on Go 1.24+ (or the program crashes)
		for _, b := range buf {
			if int(b) >= limit {
				continue // reject to keep the distribution uniform
			}
			id[i] = alphabet[int(b)%n]
			i++
			if i == length {
				break
			}
		}
	}
	return string(id), nil
}
