// Copyright IBM Corp. 2014, 2025
// SPDX-License-Identifier: MPL-2.0
// Code generated by "internal/generate/listpages/main.go -ListOps=ListTrafficPolicies -Paginator=TrafficPolicyIdMarker -- list_traffic_policies_pages_gen.go"; DO NOT EDIT.

package route53

import (
	"context"

	"github.com/YakDriver/smarterr"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/route53"
)

func listTrafficPoliciesPages(ctx context.Context, conn *route53.Client, input *route53.ListTrafficPoliciesInput, fn func(*route53.ListTrafficPoliciesOutput, bool) bool, optFns ...func(*route53.Options)) error {
	for {
		output, err := conn.ListTrafficPolicies(ctx, input, optFns...)
		if err != nil {
			return smarterr.NewError(err)
		}

		lastPage := aws.ToString(output.TrafficPolicyIdMarker) == ""
		if !fn(output, lastPage) || lastPage {
			break
		}

		input.TrafficPolicyIdMarker = output.TrafficPolicyIdMarker
	}
	return nil
}
