// Code generated by smithy-go-codegen DO NOT EDIT.

package lambdaweb

import (
	"context"
	"errors"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/lambdaweb/schemas"
	"github.com/aws/aws-sdk-go-v2/service/lambdaweb/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
	smithytime "github.com/aws/smithy-go/time"
	smithywaiter "github.com/aws/smithy-go/waiter"
	"time"
)

// Retrieves details about a web function endpoint, including its current state,
// configuration, and domain name.
func (c *Client) GetWebFunctionEndpoint(ctx context.Context, params *GetWebFunctionEndpointInput, optFns ...func(*Options)) (*GetWebFunctionEndpointOutput, error) {
	if params == nil {
		params = &GetWebFunctionEndpointInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "GetWebFunctionEndpoint", params, optFns, c.addOperationGetWebFunctionEndpointMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*GetWebFunctionEndpointOutput)
	out.ResultMetadata = metadata
	return out, nil
}

// The request to retrieve a web function endpoint.
type GetWebFunctionEndpointInput struct {

	// The name of the endpoint to retrieve. You can specify the endpoint name or the
	// endpoint ARN. The maximum length is 256 characters.
	//
	// This member is required.
	EndpointName *string

	// The name of the web function. You can specify the function name or the function
	// ARN. The maximum length is 256 characters.
	//
	// This member is required.
	FunctionName *string

	noSmithyDocumentSerde
}

func (v *GetWebFunctionEndpointInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.GetWebFunctionEndpointRequest)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *GetWebFunctionEndpointInput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.EndpointName != nil {
		s.WriteString(schemas.GetWebFunctionEndpointRequest_endpointName, *v.EndpointName)
	}
	if v.FunctionName != nil {
		s.WriteString(schemas.GetWebFunctionEndpointRequest_functionName, *v.FunctionName)
	}
}

// Contains details about the web function endpoint.
type GetWebFunctionEndpointOutput struct {

	// The authorization type for a web function endpoint. Possible values:
	// ApplicationManaged (the function handles authorization), IamAuth (Lambda
	// authorizes requests with AWS SigV4 and IAM).
	//
	// This member is required.
	AuthType types.AuthType

	// The auto-deployment mode for a web function endpoint. Possible values:
	// LatestRevision (endpoint automatically serves the newest revision), Disabled
	// (revision routing is fixed until explicitly changed).
	//
	// This member is required.
	AutoDeploymentMode types.AutoDeploymentMode

	// The date and time the endpoint was created.
	//
	// This member is required.
	CreatedAt *time.Time

	// The domain name assigned to the endpoint.
	//
	// This member is required.
	DomainName *string

	// The ARN of the endpoint.
	//
	// This member is required.
	EndpointArn *string

	// The name of the endpoint.
	//
	// This member is required.
	EndpointName *string

	// The type of a web function endpoint. Possible values: HomeRegion (serves from
	// the Region where the function was created), MultiRegion (replicates across
	// chosen Regions and routes to the nearest), PerRegion (separate endpoint per
	// Region).
	//
	// This member is required.
	EndpointType types.EndpointType

	// The ARN of the web function.
	//
	// This member is required.
	FunctionArn *string

	// The list of regional endpoint configurations.
	//
	// This member is required.
	RegionalEndpoints map[string]types.RegionalEndpoint

	// The Regions configured for the endpoint.
	//
	// This member is required.
	Regions []string

	// The traffic distribution across revisions for the endpoint. Each entry maps a
	// revision to a weight from 1 to 100.
	//
	// This member is required.
	RevisionWeights []types.RevisionWeight

	// The current state of the endpoint.
	//
	// This member is required.
	State types.EndpointState

	// The reason for the current state of the endpoint.
	//
	// This member is required.
	StateReason *string

	// The date and time the endpoint was last updated.
	//
	// This member is required.
	UpdatedAt *time.Time

	// The description of the endpoint.
	Description *string

	// The scaling configuration for a web function endpoint.
	ScalingConfig *types.ScalingConfig

	// The throttling configuration for a web function endpoint.
	ThrottleConfig *types.ThrottleConfig

	// The status of the most recent update to an endpoint. Possible values: InProgress
	// (update is in progress), Successful (update completed successfully), Failed
	// (update failed).
	UpdateStatus types.EndpointUpdateStatus

	// The reason for the endpoint's most recent update status.
	UpdateStatusReason *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *GetWebFunctionEndpointOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteStruct(schemas.GetWebFunctionEndpointResponse)
	v.SerializeMembers(s)
	s.CloseStruct()
}

func (v *GetWebFunctionEndpointOutput) SerializeMembers(s smithy.ShapeSerializer) {
	if v.AuthType != "" {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_authType, string(v.AuthType))
	}
	if v.AutoDeploymentMode != "" {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_autoDeploymentMode, string(v.AutoDeploymentMode))
	}
	if v.CreatedAt != nil {
		s.WriteTime(schemas.GetWebFunctionEndpointResponse_createdAt, *v.CreatedAt)
	}
	if v.Description != nil {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_description, *v.Description)
	}
	if v.DomainName != nil {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_domainName, *v.DomainName)
	}
	if v.EndpointArn != nil {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_endpointArn, *v.EndpointArn)
	}
	if v.EndpointName != nil {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_endpointName, *v.EndpointName)
	}
	if v.EndpointType != "" {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_endpointType, string(v.EndpointType))
	}
	if v.FunctionArn != nil {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_functionArn, *v.FunctionArn)
	}
	serializeRegionalEndpoints(s, schemas.GetWebFunctionEndpointResponse_regionalEndpoints, v.RegionalEndpoints)
	serializeRegionList(s, schemas.GetWebFunctionEndpointResponse_regions, v.Regions)
	serializeRevisionWeightList(s, schemas.GetWebFunctionEndpointResponse_revisionWeights, v.RevisionWeights)
	if v.ScalingConfig != nil {
		s.WriteStruct(schemas.GetWebFunctionEndpointResponse_scalingConfig)
		v.ScalingConfig.SerializeMembers(s)
		s.CloseStruct()
	}
	if v.State != "" {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_state, string(v.State))
	}
	if v.StateReason != nil {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_stateReason, *v.StateReason)
	}
	if v.ThrottleConfig != nil {
		s.WriteStruct(schemas.GetWebFunctionEndpointResponse_throttleConfig)
		v.ThrottleConfig.SerializeMembers(s)
		s.CloseStruct()
	}
	if v.UpdateStatus != "" {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_updateStatus, string(v.UpdateStatus))
	}
	if v.UpdateStatusReason != nil {
		s.WriteString(schemas.GetWebFunctionEndpointResponse_updateStatusReason, *v.UpdateStatusReason)
	}
	if v.UpdatedAt != nil {
		s.WriteTime(schemas.GetWebFunctionEndpointResponse_updatedAt, *v.UpdatedAt)
	}
}
func (v *GetWebFunctionEndpointOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.GetWebFunctionEndpointResponse, func(s *smithy.Schema) error {
		switch s {
		case schemas.GetWebFunctionEndpointResponse_authType:
			var ev string
			if err := d.ReadString(schemas.GetWebFunctionEndpointResponse_authType, &ev); err != nil {
				return err
			}
			v.AuthType = types.AuthType(ev)
			return nil
		case schemas.GetWebFunctionEndpointResponse_autoDeploymentMode:
			var ev string
			if err := d.ReadString(schemas.GetWebFunctionEndpointResponse_autoDeploymentMode, &ev); err != nil {
				return err
			}
			v.AutoDeploymentMode = types.AutoDeploymentMode(ev)
			return nil
		case schemas.GetWebFunctionEndpointResponse_createdAt:
			v.CreatedAt = new(time.Time)
			return d.ReadTime(schemas.GetWebFunctionEndpointResponse_createdAt, v.CreatedAt)
		case schemas.GetWebFunctionEndpointResponse_description:
			v.Description = new(string)
			return d.ReadString(schemas.GetWebFunctionEndpointResponse_description, v.Description)
		case schemas.GetWebFunctionEndpointResponse_domainName:
			v.DomainName = new(string)
			return d.ReadString(schemas.GetWebFunctionEndpointResponse_domainName, v.DomainName)
		case schemas.GetWebFunctionEndpointResponse_endpointArn:
			v.EndpointArn = new(string)
			return d.ReadString(schemas.GetWebFunctionEndpointResponse_endpointArn, v.EndpointArn)
		case schemas.GetWebFunctionEndpointResponse_endpointName:
			v.EndpointName = new(string)
			return d.ReadString(schemas.GetWebFunctionEndpointResponse_endpointName, v.EndpointName)
		case schemas.GetWebFunctionEndpointResponse_endpointType:
			var ev string
			if err := d.ReadString(schemas.GetWebFunctionEndpointResponse_endpointType, &ev); err != nil {
				return err
			}
			v.EndpointType = types.EndpointType(ev)
			return nil
		case schemas.GetWebFunctionEndpointResponse_functionArn:
			v.FunctionArn = new(string)
			return d.ReadString(schemas.GetWebFunctionEndpointResponse_functionArn, v.FunctionArn)
		case schemas.GetWebFunctionEndpointResponse_regionalEndpoints:
			return deserializeRegionalEndpoints(d, schemas.GetWebFunctionEndpointResponse_regionalEndpoints, &v.RegionalEndpoints)
		case schemas.GetWebFunctionEndpointResponse_regions:
			return deserializeRegionList(d, schemas.GetWebFunctionEndpointResponse_regions, &v.Regions)
		case schemas.GetWebFunctionEndpointResponse_revisionWeights:
			return deserializeRevisionWeightList(d, schemas.GetWebFunctionEndpointResponse_revisionWeights, &v.RevisionWeights)
		case schemas.GetWebFunctionEndpointResponse_scalingConfig:
			v.ScalingConfig = &types.ScalingConfig{}
			return v.ScalingConfig.Deserialize(d)
		case schemas.GetWebFunctionEndpointResponse_state:
			var ev string
			if err := d.ReadString(schemas.GetWebFunctionEndpointResponse_state, &ev); err != nil {
				return err
			}
			v.State = types.EndpointState(ev)
			return nil
		case schemas.GetWebFunctionEndpointResponse_stateReason:
			v.StateReason = new(string)
			return d.ReadString(schemas.GetWebFunctionEndpointResponse_stateReason, v.StateReason)
		case schemas.GetWebFunctionEndpointResponse_throttleConfig:
			v.ThrottleConfig = &types.ThrottleConfig{}
			return v.ThrottleConfig.Deserialize(d)
		case schemas.GetWebFunctionEndpointResponse_updateStatus:
			var ev string
			if err := d.ReadString(schemas.GetWebFunctionEndpointResponse_updateStatus, &ev); err != nil {
				return err
			}
			v.UpdateStatus = types.EndpointUpdateStatus(ev)
			return nil
		case schemas.GetWebFunctionEndpointResponse_updateStatusReason:
			v.UpdateStatusReason = new(string)
			return d.ReadString(schemas.GetWebFunctionEndpointResponse_updateStatusReason, v.UpdateStatusReason)
		case schemas.GetWebFunctionEndpointResponse_updatedAt:
			v.UpdatedAt = new(time.Time)
			return d.ReadTime(schemas.GetWebFunctionEndpointResponse_updatedAt, v.UpdatedAt)
		}
		return nil
	})
}
func (c *Client) addOperationGetWebFunctionEndpointMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.GetWebFunctionEndpoint, schemas.GetWebFunctionEndpointRequest, schemas.GetWebFunctionEndpointResponse)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.GetWebFunctionEndpoint, schemas.GetWebFunctionEndpointRequest, schemas.GetWebFunctionEndpointResponse), output: &GetWebFunctionEndpointOutput{}}, middleware.After); err != nil {
		return err
	}

	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpGetWebFunctionEndpointValidationMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

// WebFunctionEndpointActiveWaiterOptions are waiter options for
// WebFunctionEndpointActiveWaiter
type WebFunctionEndpointActiveWaiterOptions struct {

	// Set of options to modify how an operation is invoked. These apply to all
	// operations invoked for this client. Use functional options on operation call to
	// modify this list for per operation behavior.
	//
	// Passing options here is functionally equivalent to passing values to this
	// config's ClientOptions field that extend the inner client's APIOptions directly.
	APIOptions []func(*middleware.Stack) error

	// Functional options to be passed to all operations invoked by this client.
	//
	// Function values that modify the inner APIOptions are applied after the waiter
	// config's own APIOptions modifiers.
	ClientOptions []func(*Options)

	// MinDelay is the minimum amount of time to delay between retries. If unset,
	// WebFunctionEndpointActiveWaiter will use default minimum delay of 1 seconds.
	// Note that MinDelay must resolve to a value lesser than or equal to the MaxDelay.
	MinDelay time.Duration

	// MaxDelay is the maximum amount of time to delay between retries. If unset or
	// set to zero, WebFunctionEndpointActiveWaiter will use default max delay of 300
	// seconds. Note that MaxDelay must resolve to value greater than or equal to the
	// MinDelay.
	MaxDelay time.Duration

	// LogWaitAttempts is used to enable logging for waiter retry attempts
	LogWaitAttempts bool

	// Retryable is function that can be used to override the service defined
	// waiter-behavior based on operation output, or returned error. This function is
	// used by the waiter to decide if a state is retryable or a terminal state.
	//
	// By default service-modeled logic will populate this option. This option can
	// thus be used to define a custom waiter state with fall-back to service-modeled
	// waiter state mutators.The function returns an error in case of a failure state.
	// In case of retry state, this function returns a bool value of true and nil
	// error, while in case of success it returns a bool value of false and nil error.
	Retryable func(context.Context, *GetWebFunctionEndpointInput, *GetWebFunctionEndpointOutput, error) (bool, error)
}

// WebFunctionEndpointActiveWaiter defines the waiters for
// WebFunctionEndpointActive
type WebFunctionEndpointActiveWaiter struct {
	client GetWebFunctionEndpointAPIClient

	options WebFunctionEndpointActiveWaiterOptions
}

// NewWebFunctionEndpointActiveWaiter constructs a WebFunctionEndpointActiveWaiter.
func NewWebFunctionEndpointActiveWaiter(client GetWebFunctionEndpointAPIClient, optFns ...func(*WebFunctionEndpointActiveWaiterOptions)) *WebFunctionEndpointActiveWaiter {
	options := WebFunctionEndpointActiveWaiterOptions{}
	options.MinDelay = 1 * time.Second
	options.MaxDelay = 300 * time.Second
	options.Retryable = webFunctionEndpointActiveStateRetryable

	for _, fn := range optFns {
		fn(&options)
	}
	return &WebFunctionEndpointActiveWaiter{
		client:  client,
		options: options,
	}
}

// Wait calls the waiter function for WebFunctionEndpointActive waiter. The
// maxWaitDur is the maximum wait duration the waiter will wait. The maxWaitDur is
// required and must be greater than zero.
func (w *WebFunctionEndpointActiveWaiter) Wait(ctx context.Context, params *GetWebFunctionEndpointInput, maxWaitDur time.Duration, optFns ...func(*WebFunctionEndpointActiveWaiterOptions)) error {
	_, err := w.WaitForOutput(ctx, params, maxWaitDur, optFns...)
	return err
}

// WaitForOutput calls the waiter function for WebFunctionEndpointActive waiter
// and returns the output of the successful operation. The maxWaitDur is the
// maximum wait duration the waiter will wait. The maxWaitDur is required and must
// be greater than zero.
func (w *WebFunctionEndpointActiveWaiter) WaitForOutput(ctx context.Context, params *GetWebFunctionEndpointInput, maxWaitDur time.Duration, optFns ...func(*WebFunctionEndpointActiveWaiterOptions)) (*GetWebFunctionEndpointOutput, error) {
	if maxWaitDur <= 0 {
		return nil, fmt.Errorf("maximum wait time for waiter must be greater than zero")
	}

	options := w.options
	for _, fn := range optFns {
		fn(&options)
	}

	if options.MaxDelay <= 0 {
		options.MaxDelay = 300 * time.Second
	}

	if options.MinDelay > options.MaxDelay {
		return nil, fmt.Errorf("minimum waiter delay %v must be lesser than or equal to maximum waiter delay of %v.", options.MinDelay, options.MaxDelay)
	}

	ctx, cancelFn := context.WithTimeout(ctx, maxWaitDur)
	defer cancelFn()

	logger := smithywaiter.Logger{}
	remainingTime := maxWaitDur

	var attempt int64
	for {

		attempt++
		apiOptions := options.APIOptions
		start := time.Now()

		if options.LogWaitAttempts {
			logger.Attempt = attempt
			apiOptions = append([]func(*middleware.Stack) error{}, options.APIOptions...)
			apiOptions = append(apiOptions, logger.AddLogger)
		}

		out, err := w.client.GetWebFunctionEndpoint(ctx, params, func(o *Options) {
			baseOpts := []func(*Options){
				addIsWaiterUserAgent,
			}
			o.APIOptions = append(o.APIOptions, apiOptions...)
			for _, opt := range baseOpts {
				opt(o)
			}
			for _, opt := range options.ClientOptions {
				opt(o)
			}
		})

		retryable, err := options.Retryable(ctx, params, out, err)
		if err != nil {
			return nil, err
		}
		if !retryable {
			return out, nil
		}

		remainingTime -= time.Since(start)
		if remainingTime < options.MinDelay || remainingTime <= 0 {
			break
		}

		// compute exponential backoff between waiter retries
		delay, err := smithywaiter.ComputeDelay(
			attempt, options.MinDelay, options.MaxDelay, remainingTime,
		)
		if err != nil {
			return nil, fmt.Errorf("error computing waiter delay, %w", err)
		}

		remainingTime -= delay
		// sleep for the delay amount before invoking a request
		if err := smithytime.SleepWithContext(ctx, delay); err != nil {
			return nil, fmt.Errorf("request cancelled while waiting, %w", err)
		}
	}
	return nil, fmt.Errorf("exceeded max wait time for WebFunctionEndpointActive waiter")
}

func webFunctionEndpointActiveStateRetryable(ctx context.Context, input *GetWebFunctionEndpointInput, output *GetWebFunctionEndpointOutput, err error) (bool, error) {

	if err == nil {
		v1 := output.State
		expectedValue := "Active"
		var pathValue string
		pathValue = string(v1)
		if pathValue == expectedValue {
			return false, nil
		}
	}

	if err == nil {
		v1 := output.State
		expectedValue := "Failed"
		var pathValue string
		pathValue = string(v1)
		if pathValue == expectedValue {
			return false, fmt.Errorf("waiter state transitioned to Failure")
		}
	}

	if err == nil {
		v1 := output.State
		expectedValue := "Deleting"
		var pathValue string
		pathValue = string(v1)
		if pathValue == expectedValue {
			return false, fmt.Errorf("waiter state transitioned to Failure")
		}
	}

	if err == nil {
		v1 := output.State
		expectedValue := "Pending"
		var pathValue string
		pathValue = string(v1)
		if pathValue == expectedValue {
			return true, nil
		}
	}

	if err != nil {
		return false, err
	}
	return true, nil
}

// WebFunctionEndpointDeletedWaiterOptions are waiter options for
// WebFunctionEndpointDeletedWaiter
type WebFunctionEndpointDeletedWaiterOptions struct {

	// Set of options to modify how an operation is invoked. These apply to all
	// operations invoked for this client. Use functional options on operation call to
	// modify this list for per operation behavior.
	//
	// Passing options here is functionally equivalent to passing values to this
	// config's ClientOptions field that extend the inner client's APIOptions directly.
	APIOptions []func(*middleware.Stack) error

	// Functional options to be passed to all operations invoked by this client.
	//
	// Function values that modify the inner APIOptions are applied after the waiter
	// config's own APIOptions modifiers.
	ClientOptions []func(*Options)

	// MinDelay is the minimum amount of time to delay between retries. If unset,
	// WebFunctionEndpointDeletedWaiter will use default minimum delay of 1 seconds.
	// Note that MinDelay must resolve to a value lesser than or equal to the MaxDelay.
	MinDelay time.Duration

	// MaxDelay is the maximum amount of time to delay between retries. If unset or
	// set to zero, WebFunctionEndpointDeletedWaiter will use default max delay of 300
	// seconds. Note that MaxDelay must resolve to value greater than or equal to the
	// MinDelay.
	MaxDelay time.Duration

	// LogWaitAttempts is used to enable logging for waiter retry attempts
	LogWaitAttempts bool

	// Retryable is function that can be used to override the service defined
	// waiter-behavior based on operation output, or returned error. This function is
	// used by the waiter to decide if a state is retryable or a terminal state.
	//
	// By default service-modeled logic will populate this option. This option can
	// thus be used to define a custom waiter state with fall-back to service-modeled
	// waiter state mutators.The function returns an error in case of a failure state.
	// In case of retry state, this function returns a bool value of true and nil
	// error, while in case of success it returns a bool value of false and nil error.
	Retryable func(context.Context, *GetWebFunctionEndpointInput, *GetWebFunctionEndpointOutput, error) (bool, error)
}

// WebFunctionEndpointDeletedWaiter defines the waiters for
// WebFunctionEndpointDeleted
type WebFunctionEndpointDeletedWaiter struct {
	client GetWebFunctionEndpointAPIClient

	options WebFunctionEndpointDeletedWaiterOptions
}

// NewWebFunctionEndpointDeletedWaiter constructs a
// WebFunctionEndpointDeletedWaiter.
func NewWebFunctionEndpointDeletedWaiter(client GetWebFunctionEndpointAPIClient, optFns ...func(*WebFunctionEndpointDeletedWaiterOptions)) *WebFunctionEndpointDeletedWaiter {
	options := WebFunctionEndpointDeletedWaiterOptions{}
	options.MinDelay = 1 * time.Second
	options.MaxDelay = 300 * time.Second
	options.Retryable = webFunctionEndpointDeletedStateRetryable

	for _, fn := range optFns {
		fn(&options)
	}
	return &WebFunctionEndpointDeletedWaiter{
		client:  client,
		options: options,
	}
}

// Wait calls the waiter function for WebFunctionEndpointDeleted waiter. The
// maxWaitDur is the maximum wait duration the waiter will wait. The maxWaitDur is
// required and must be greater than zero.
func (w *WebFunctionEndpointDeletedWaiter) Wait(ctx context.Context, params *GetWebFunctionEndpointInput, maxWaitDur time.Duration, optFns ...func(*WebFunctionEndpointDeletedWaiterOptions)) error {
	_, err := w.WaitForOutput(ctx, params, maxWaitDur, optFns...)
	return err
}

// WaitForOutput calls the waiter function for WebFunctionEndpointDeleted waiter
// and returns the output of the successful operation. The maxWaitDur is the
// maximum wait duration the waiter will wait. The maxWaitDur is required and must
// be greater than zero.
func (w *WebFunctionEndpointDeletedWaiter) WaitForOutput(ctx context.Context, params *GetWebFunctionEndpointInput, maxWaitDur time.Duration, optFns ...func(*WebFunctionEndpointDeletedWaiterOptions)) (*GetWebFunctionEndpointOutput, error) {
	if maxWaitDur <= 0 {
		return nil, fmt.Errorf("maximum wait time for waiter must be greater than zero")
	}

	options := w.options
	for _, fn := range optFns {
		fn(&options)
	}

	if options.MaxDelay <= 0 {
		options.MaxDelay = 300 * time.Second
	}

	if options.MinDelay > options.MaxDelay {
		return nil, fmt.Errorf("minimum waiter delay %v must be lesser than or equal to maximum waiter delay of %v.", options.MinDelay, options.MaxDelay)
	}

	ctx, cancelFn := context.WithTimeout(ctx, maxWaitDur)
	defer cancelFn()

	logger := smithywaiter.Logger{}
	remainingTime := maxWaitDur

	var attempt int64
	for {

		attempt++
		apiOptions := options.APIOptions
		start := time.Now()

		if options.LogWaitAttempts {
			logger.Attempt = attempt
			apiOptions = append([]func(*middleware.Stack) error{}, options.APIOptions...)
			apiOptions = append(apiOptions, logger.AddLogger)
		}

		out, err := w.client.GetWebFunctionEndpoint(ctx, params, func(o *Options) {
			baseOpts := []func(*Options){
				addIsWaiterUserAgent,
			}
			o.APIOptions = append(o.APIOptions, apiOptions...)
			for _, opt := range baseOpts {
				opt(o)
			}
			for _, opt := range options.ClientOptions {
				opt(o)
			}
		})

		retryable, err := options.Retryable(ctx, params, out, err)
		if err != nil {
			return nil, err
		}
		if !retryable {
			return out, nil
		}

		remainingTime -= time.Since(start)
		if remainingTime < options.MinDelay || remainingTime <= 0 {
			break
		}

		// compute exponential backoff between waiter retries
		delay, err := smithywaiter.ComputeDelay(
			attempt, options.MinDelay, options.MaxDelay, remainingTime,
		)
		if err != nil {
			return nil, fmt.Errorf("error computing waiter delay, %w", err)
		}

		remainingTime -= delay
		// sleep for the delay amount before invoking a request
		if err := smithytime.SleepWithContext(ctx, delay); err != nil {
			return nil, fmt.Errorf("request cancelled while waiting, %w", err)
		}
	}
	return nil, fmt.Errorf("exceeded max wait time for WebFunctionEndpointDeleted waiter")
}

func webFunctionEndpointDeletedStateRetryable(ctx context.Context, input *GetWebFunctionEndpointInput, output *GetWebFunctionEndpointOutput, err error) (bool, error) {

	if err != nil {
		var errorType *types.ResourceNotFoundException
		if errors.As(err, &errorType) {
			return false, nil
		}
	}

	if err == nil {
		v1 := output.State
		expectedValue := "Deleting"
		var pathValue string
		pathValue = string(v1)
		if pathValue == expectedValue {
			return true, nil
		}
	}

	if err != nil {
		return false, err
	}
	return true, nil
}

// WebFunctionEndpointUpdatedWaiterOptions are waiter options for
// WebFunctionEndpointUpdatedWaiter
type WebFunctionEndpointUpdatedWaiterOptions struct {

	// Set of options to modify how an operation is invoked. These apply to all
	// operations invoked for this client. Use functional options on operation call to
	// modify this list for per operation behavior.
	//
	// Passing options here is functionally equivalent to passing values to this
	// config's ClientOptions field that extend the inner client's APIOptions directly.
	APIOptions []func(*middleware.Stack) error

	// Functional options to be passed to all operations invoked by this client.
	//
	// Function values that modify the inner APIOptions are applied after the waiter
	// config's own APIOptions modifiers.
	ClientOptions []func(*Options)

	// MinDelay is the minimum amount of time to delay between retries. If unset,
	// WebFunctionEndpointUpdatedWaiter will use default minimum delay of 1 seconds.
	// Note that MinDelay must resolve to a value lesser than or equal to the MaxDelay.
	MinDelay time.Duration

	// MaxDelay is the maximum amount of time to delay between retries. If unset or
	// set to zero, WebFunctionEndpointUpdatedWaiter will use default max delay of 300
	// seconds. Note that MaxDelay must resolve to value greater than or equal to the
	// MinDelay.
	MaxDelay time.Duration

	// LogWaitAttempts is used to enable logging for waiter retry attempts
	LogWaitAttempts bool

	// Retryable is function that can be used to override the service defined
	// waiter-behavior based on operation output, or returned error. This function is
	// used by the waiter to decide if a state is retryable or a terminal state.
	//
	// By default service-modeled logic will populate this option. This option can
	// thus be used to define a custom waiter state with fall-back to service-modeled
	// waiter state mutators.The function returns an error in case of a failure state.
	// In case of retry state, this function returns a bool value of true and nil
	// error, while in case of success it returns a bool value of false and nil error.
	Retryable func(context.Context, *GetWebFunctionEndpointInput, *GetWebFunctionEndpointOutput, error) (bool, error)
}

// WebFunctionEndpointUpdatedWaiter defines the waiters for
// WebFunctionEndpointUpdated
type WebFunctionEndpointUpdatedWaiter struct {
	client GetWebFunctionEndpointAPIClient

	options WebFunctionEndpointUpdatedWaiterOptions
}

// NewWebFunctionEndpointUpdatedWaiter constructs a
// WebFunctionEndpointUpdatedWaiter.
func NewWebFunctionEndpointUpdatedWaiter(client GetWebFunctionEndpointAPIClient, optFns ...func(*WebFunctionEndpointUpdatedWaiterOptions)) *WebFunctionEndpointUpdatedWaiter {
	options := WebFunctionEndpointUpdatedWaiterOptions{}
	options.MinDelay = 1 * time.Second
	options.MaxDelay = 300 * time.Second
	options.Retryable = webFunctionEndpointUpdatedStateRetryable

	for _, fn := range optFns {
		fn(&options)
	}
	return &WebFunctionEndpointUpdatedWaiter{
		client:  client,
		options: options,
	}
}

// Wait calls the waiter function for WebFunctionEndpointUpdated waiter. The
// maxWaitDur is the maximum wait duration the waiter will wait. The maxWaitDur is
// required and must be greater than zero.
func (w *WebFunctionEndpointUpdatedWaiter) Wait(ctx context.Context, params *GetWebFunctionEndpointInput, maxWaitDur time.Duration, optFns ...func(*WebFunctionEndpointUpdatedWaiterOptions)) error {
	_, err := w.WaitForOutput(ctx, params, maxWaitDur, optFns...)
	return err
}

// WaitForOutput calls the waiter function for WebFunctionEndpointUpdated waiter
// and returns the output of the successful operation. The maxWaitDur is the
// maximum wait duration the waiter will wait. The maxWaitDur is required and must
// be greater than zero.
func (w *WebFunctionEndpointUpdatedWaiter) WaitForOutput(ctx context.Context, params *GetWebFunctionEndpointInput, maxWaitDur time.Duration, optFns ...func(*WebFunctionEndpointUpdatedWaiterOptions)) (*GetWebFunctionEndpointOutput, error) {
	if maxWaitDur <= 0 {
		return nil, fmt.Errorf("maximum wait time for waiter must be greater than zero")
	}

	options := w.options
	for _, fn := range optFns {
		fn(&options)
	}

	if options.MaxDelay <= 0 {
		options.MaxDelay = 300 * time.Second
	}

	if options.MinDelay > options.MaxDelay {
		return nil, fmt.Errorf("minimum waiter delay %v must be lesser than or equal to maximum waiter delay of %v.", options.MinDelay, options.MaxDelay)
	}

	ctx, cancelFn := context.WithTimeout(ctx, maxWaitDur)
	defer cancelFn()

	logger := smithywaiter.Logger{}
	remainingTime := maxWaitDur

	var attempt int64
	for {

		attempt++
		apiOptions := options.APIOptions
		start := time.Now()

		if options.LogWaitAttempts {
			logger.Attempt = attempt
			apiOptions = append([]func(*middleware.Stack) error{}, options.APIOptions...)
			apiOptions = append(apiOptions, logger.AddLogger)
		}

		out, err := w.client.GetWebFunctionEndpoint(ctx, params, func(o *Options) {
			baseOpts := []func(*Options){
				addIsWaiterUserAgent,
			}
			o.APIOptions = append(o.APIOptions, apiOptions...)
			for _, opt := range baseOpts {
				opt(o)
			}
			for _, opt := range options.ClientOptions {
				opt(o)
			}
		})

		retryable, err := options.Retryable(ctx, params, out, err)
		if err != nil {
			return nil, err
		}
		if !retryable {
			return out, nil
		}

		remainingTime -= time.Since(start)
		if remainingTime < options.MinDelay || remainingTime <= 0 {
			break
		}

		// compute exponential backoff between waiter retries
		delay, err := smithywaiter.ComputeDelay(
			attempt, options.MinDelay, options.MaxDelay, remainingTime,
		)
		if err != nil {
			return nil, fmt.Errorf("error computing waiter delay, %w", err)
		}

		remainingTime -= delay
		// sleep for the delay amount before invoking a request
		if err := smithytime.SleepWithContext(ctx, delay); err != nil {
			return nil, fmt.Errorf("request cancelled while waiting, %w", err)
		}
	}
	return nil, fmt.Errorf("exceeded max wait time for WebFunctionEndpointUpdated waiter")
}

func webFunctionEndpointUpdatedStateRetryable(ctx context.Context, input *GetWebFunctionEndpointInput, output *GetWebFunctionEndpointOutput, err error) (bool, error) {

	if err == nil {
		v1 := output.UpdateStatus
		expectedValue := "Successful"
		var pathValue string
		pathValue = string(v1)
		if pathValue == expectedValue {
			return false, nil
		}
	}

	if err == nil {
		v1 := output.UpdateStatus
		expectedValue := "Failed"
		var pathValue string
		pathValue = string(v1)
		if pathValue == expectedValue {
			return false, fmt.Errorf("waiter state transitioned to Failure")
		}
	}

	if err == nil {
		v1 := output.UpdateStatus
		expectedValue := "InProgress"
		var pathValue string
		pathValue = string(v1)
		if pathValue == expectedValue {
			return true, nil
		}
	}

	if err != nil {
		return false, err
	}
	return true, nil
}

// GetWebFunctionEndpointAPIClient is a client that implements the
// GetWebFunctionEndpoint operation.
type GetWebFunctionEndpointAPIClient interface {
	GetWebFunctionEndpoint(context.Context, *GetWebFunctionEndpointInput, ...func(*Options)) (*GetWebFunctionEndpointOutput, error)
}

var _ GetWebFunctionEndpointAPIClient = (*Client)(nil)
