// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

package schema

// Schema attribute name constants used across QuickSight schemas.
const (
	attrAggregationFunction  = "aggregation_function"
	attrAvailabilityStatus   = "availability_status"
	attrAxisBinding          = "axis_binding"
	attrCanvasSizeOptions    = "canvas_size_options"
	attrCategory             = "category"
	attrCategoryItemsLimit   = "category_items_limit"
	attrCategoryLabelOptions = "category_label_options"
	attrCategorySort         = "category_sort"
	attrChartConfiguration   = "chart_configuration"
	attrColor                = "color"
	attrColors               = "colors"
	attrColumn               = "column"
	attrColumnHierarchies    = "column_hierarchies"
	attrColumnName           = "column_name"
	attrColumns              = "columns"
	attrComputationID        = "computation_id"
	attrCustomLabel          = "custom_label"
	attrDataLabels           = "data_labels"
	attrDataSetIdentifier    = "data_set_identifier"
	attrDefinition           = "definition"
	attrDisplayOptions       = "display_options"
	attrFieldID              = "field_id"
	attrFieldWells           = "field_wells"
	attrFilterControlID      = "filter_control_id"
	attrFilterID             = "filter_id"
	attrFontConfiguration    = "font_configuration"
	attrFormatConfiguration  = "format_configuration"
	attrHierarchyID          = "hierarchy_id"
	attrHost                 = "host"
	attrIcon                 = "icon"
	attrLegend               = "legend"
	attrNullOption           = "null_option"
	attrParameterControlID   = "parameter_control_id"
	attrParameterName        = "parameter_name"
	attrSelectAllOptions     = "select_all_options"
	attrSortConfiguration    = "sort_configuration"
	attrSourceEntity         = "source_entity"
	attrSourceFilterID       = "source_filter_id"
	attrSourceParameterName  = "source_parameter_name"
	attrSubtitle             = "subtitle"
	attrTextColor            = "text_color"
	attrTime                 = "time"
	attrTimeGranularity      = "time_granularity"
	attrTitle                = "title"
	attrTitleOptions         = "title_options"
	attrToolTip              = "tooltip"
	attrVisibility           = "visibility"
	attrVisualID             = "visual_id"
	attrVisualPalette        = "visual_palette"
)
