# Copyright IBM Corp. 2014, 2026
# SPDX-License-Identifier: MPL-2.0

provider_source = "registry.terraform.io/hashicorp/aws"
provider_dir    = "."
schema_json     = "terraform-providers-schema/schema.json"

file_aliases = {
  "list_resource/aws_ebs_volume" = "aws_ec2_ebs_volume"
}

ignore_contents_check = [
  "data_source/aws_kms_secret",
]

# ─── Type overrides ─────────────────────────────────────────────────────────
# Define bylines, frontmatter requirements, and other AWS-specific conventions.

type "resource" {
  schema_kind   = "resource"
  website_paths = ["website/docs/r/{name}.html.markdown"]
  title_prefix  = "Resource"

  arguments_bylines = [
    "This resource supports the following arguments:",
    "The following arguments are required:",
    "The following arguments are optional:",
    "This resource does not support any arguments.",
  ]
  attributes_bylines = [
    "This resource exports the following attributes in addition to the arguments above:",
    "This resource exports no additional attributes.",
  ]

  require_attributes = "required"
  require_import     = "optional"
  require_timeouts   = "optional"
  require_signature  = "forbidden"

  frontmatter_require = ["description", "page_title"]
  frontmatter_forbid  = ["sidebar_current"]

  region_aware = true
}

type "data_source" {
  schema_kind   = "data_source"
  website_paths = ["website/docs/d/{name}.html.markdown"]
  title_prefix  = "Data Source"

  arguments_bylines = [
    "This data source supports the following arguments:",
    "The following arguments are required:",
    "The following arguments are optional:",
    "This data source does not support any arguments.",
  ]
  attributes_bylines = [
    "This data source exports the following attributes in addition to the arguments above:",
    "This data source exports no additional attributes.",
  ]

  require_attributes = "required"
  require_import     = "forbidden"
  require_timeouts   = "optional"
  require_signature  = "forbidden"

  frontmatter_require = ["description", "page_title"]
  frontmatter_forbid  = ["sidebar_current"]

  region_aware = true
}

type "ephemeral" {
  schema_kind   = "ephemeral"
  website_paths = ["website/docs/ephemeral-resources/{name}.html.markdown"]
  title_prefix  = "Ephemeral"

  arguments_bylines = [
    "This ephemeral resource supports the following arguments:",
    "The following arguments are required:",
    "The following arguments are optional:",
    "This ephemeral resource does not support any arguments.",
  ]
  attributes_bylines = [
    "This ephemeral resource exports the following attributes in addition to the arguments above:",
    "This ephemeral resource exports no additional attributes.",
  ]

  require_attributes = "required"
  require_import     = "forbidden"
  require_timeouts   = "forbidden"
  require_signature  = "forbidden"

  frontmatter_require = ["description", "page_title"]
  frontmatter_forbid  = ["sidebar_current"]

  region_aware = true
}

type "function" {
  schema_kind   = "function"
  website_paths = ["website/docs/functions/{name}.html.markdown"]
  title_prefix  = "Function"

  arguments_heading              = "Arguments"
  allow_missing_arguments_byline = true

  require_attributes = "forbidden"
  require_import     = "forbidden"
  require_timeouts   = "forbidden"
  require_signature  = "required"

  frontmatter_require = ["description", "page_title"]
  frontmatter_forbid  = ["sidebar_current"]

  region_aware = false
}

type "list_resource" {
  schema_kind   = "list_resource"
  website_paths = ["website/docs/list-resources/{name}.html.markdown"]
  title_prefix  = "List Resource"

  arguments_bylines = [
    "This list resource supports the following arguments:",
    "The following arguments are required:",
    "The following arguments are optional:",
    "This list resource does not support any arguments.",
  ]

  require_attributes = "forbidden"
  require_import     = "forbidden"
  require_timeouts   = "forbidden"
  require_signature  = "forbidden"

  frontmatter_require = ["description", "page_title"]
  frontmatter_forbid  = ["sidebar_current"]

  region_aware = true
}

type "action" {
  schema_kind   = "action"
  website_paths = ["website/docs/actions/{name}.html.markdown"]
  title_prefix  = "Action"

  arguments_bylines = [
    "This action supports the following arguments:",
    "The following arguments are required:",
    "The following arguments are optional:",
    "This action does not support any arguments.",
  ]

  require_attributes = "forbidden"
  require_import     = "forbidden"
  require_timeouts   = "forbidden"
  require_signature  = "forbidden"

  frontmatter_require = ["description", "page_title", "subcategory"]
  frontmatter_forbid  = ["sidebar_current"]

  region_aware = false
}

# ─── Check blocks ───────────────────────────────────────────────────────────

check "schema_docs" {
  enabled = true

  byline      = true
  coverage    = true
  description = false
  format      = true
  heading     = true
  labels      = true
  ordering    = false

  block_heading_styles = [
    "`{Parent}` `{Block}` Block",
    "`{Block}` Block",
    "{Block} Block",
    "{Block} block",
    "{Block} Configuration Block",
    "{Block} Argument Reference",
    "{Block} Attribute Reference",
    "{Title} Arguments",
    "{Title} Argument Reference",
    "{Title} Attribute Reference",
    "`{Block}`",
    "{Block}",
    "{Title}",
  ]

  prefer_block_heading_styles = [
    "`{Parent}` `{Block}` Block",
    "`{Block}` Block",
  ]

  ignore_targets = [
    "data_source/aws_arcregionswitch_route53_health_checks",
    "data_source/aws_arn",
    "data_source/aws_athena_named_query",
    "data_source/aws_auditmanager_control",
    "data_source/aws_auditmanager_framework",
    "data_source/aws_autoscaling_group",
    "data_source/aws_autoscaling_groups",
    "data_source/aws_availability_zone",
    "data_source/aws_availability_zones",
    "data_source/aws_backup_report_plan",
    "data_source/aws_batch_job_definition",
    "data_source/aws_batch_job_queue",
    "data_source/aws_batch_scheduling_policy",
    "data_source/aws_bedrock_custom_model",
    "data_source/aws_bedrock_custom_models",
    "data_source/aws_bedrockagent_agent_versions",
    "data_source/aws_billing_views",
    "data_source/aws_budgets_budget",
    "data_source/aws_ce_cost_category",
    "data_source/aws_ce_tags",
    "data_source/aws_cloudformation_type",
    "data_source/aws_cloudfront_connection_group",
    "data_source/aws_cloudfront_distribution",
    "data_source/aws_cloudfront_distribution_tenant",
    "data_source/aws_cloudfront_origin_access_identities",
    "data_source/aws_cloudfront_origin_access_identity",
    "data_source/aws_cloudfront_origin_request_policy",
    "data_source/aws_cloudfront_realtime_log_config",
    "data_source/aws_cloudfront_response_headers_policy",
    "data_source/aws_cloudhsm_v2_cluster",
    "data_source/aws_cloudwatch_contributor_managed_insight_rules",
    "data_source/aws_cloudwatch_event_bus",
    "data_source/aws_cloudwatch_event_connection",
    "data_source/aws_cloudwatch_log_data_protection_policy_document",
    "data_source/aws_codebuild_fleet",
    "data_source/aws_codecatalyst_dev_environment",
    "data_source/aws_cognito_user_pool",
    "data_source/aws_cognito_user_pool_client",
    "data_source/aws_connect_bot_association",
    "data_source/aws_connect_hours_of_operation",
    "data_source/aws_connect_instance",
    "data_source/aws_connect_queue",
    "data_source/aws_connect_quick_connect",
    "data_source/aws_connect_routing_profile",
    "data_source/aws_connect_user_hierarchy_group",
    "data_source/aws_connect_user_hierarchy_structure",
    "data_source/aws_connect_vocabulary",
    "data_source/aws_customer_gateway",
    "data_source/aws_datapipeline_pipeline_definition",
    "data_source/aws_datazone_environment_blueprint",
    "data_source/aws_db_cluster_snapshot",
    "data_source/aws_db_instance",
    "data_source/aws_db_instances",
    "data_source/aws_db_snapshot",
    "data_source/aws_devopsguru_notification_channel",
    "data_source/aws_directory_service_directory",
    "data_source/aws_dms_certificate",
    "data_source/aws_dms_endpoint",
    "data_source/aws_dms_replication_instance",
    "data_source/aws_dms_replication_subnet_group",
    "data_source/aws_dms_replication_task",
    "data_source/aws_dx_router_configuration",
    "data_source/aws_dynamodb_table",
    "data_source/aws_dynamodb_table_item",
    "data_source/aws_ebs_snapshot",
    "data_source/aws_ebs_snapshot_ids",
    "data_source/aws_ebs_volume",
    "data_source/aws_ebs_volumes",
    "data_source/aws_ec2_capacity_block_offering",
    "data_source/aws_ec2_client_vpn_endpoint",
    "data_source/aws_ec2_coip_pool",
    "data_source/aws_ec2_coip_pools",
    "data_source/aws_ec2_host",
    "data_source/aws_ec2_instance_type",
    "data_source/aws_ec2_instance_type_offering",
    "data_source/aws_ec2_instance_type_offerings",
    "data_source/aws_ec2_instance_types",
    "data_source/aws_ec2_local_gateway",
    "data_source/aws_ec2_local_gateway_route_table",
    "data_source/aws_ec2_local_gateway_route_tables",
    "data_source/aws_ec2_local_gateway_virtual_interface",
    "data_source/aws_ec2_local_gateway_virtual_interface_group",
    "data_source/aws_ec2_local_gateway_virtual_interface_groups",
    "data_source/aws_ec2_local_gateways",
    "data_source/aws_ec2_managed_prefix_list",
    "data_source/aws_ec2_managed_prefix_lists",
    "data_source/aws_ec2_network_insights_analysis",
    "data_source/aws_ec2_network_insights_path",
    "data_source/aws_ec2_public_ipv4_pool",
    "data_source/aws_ec2_public_ipv4_pools",
    "data_source/aws_ec2_service_link_virtual_interface",
    "data_source/aws_ec2_service_link_virtual_interfaces",
    "data_source/aws_ec2_spot_price",
    "data_source/aws_ec2_transit_gateway",
    "data_source/aws_ec2_transit_gateway_attachment",
    "data_source/aws_ec2_transit_gateway_attachments",
    "data_source/aws_ec2_transit_gateway_connect",
    "data_source/aws_ec2_transit_gateway_connect_peer",
    "data_source/aws_ec2_transit_gateway_dx_gateway_attachment",
    "data_source/aws_ec2_transit_gateway_multicast_domain",
    "data_source/aws_ec2_transit_gateway_peering_attachment",
    "data_source/aws_ec2_transit_gateway_peering_attachments",
    "data_source/aws_ec2_transit_gateway_route_table",
    "data_source/aws_ec2_transit_gateway_route_table_associations",
    "data_source/aws_ec2_transit_gateway_route_table_propagations",
    "data_source/aws_ec2_transit_gateway_route_table_routes",
    "data_source/aws_ec2_transit_gateway_route_tables",
    "data_source/aws_ec2_transit_gateway_vpc_attachment",
    "data_source/aws_ec2_transit_gateway_vpc_attachments",
    "data_source/aws_ec2_transit_gateway_vpn_attachment",
    "data_source/aws_ecr_images",
    "data_source/aws_ecr_lifecycle_policy_document",
    "data_source/aws_ecrpublic_images",
    "data_source/aws_ecs_task_execution",
    "data_source/aws_efs_access_point",
    "data_source/aws_efs_file_system",
    "data_source/aws_eip",
    "data_source/aws_eips",
    "data_source/aws_eks_access_entry",
    "data_source/aws_eks_addon",
    "data_source/aws_eks_addon_version",
    "data_source/aws_eks_cluster",
    "data_source/aws_eks_cluster_versions",
    "data_source/aws_eks_node_group",
    "data_source/aws_elastic_beanstalk_application",
    "data_source/aws_elastic_beanstalk_solution_stack",
    "data_source/aws_elasticache_cluster",
    "data_source/aws_elasticache_reserved_cache_node_offering",
    "data_source/aws_elasticache_serverless_cache",
    "data_source/aws_elasticache_user",
    "data_source/aws_elasticsearch_domain",
    "data_source/aws_elb",
    "data_source/aws_emr_release_labels",
    "data_source/aws_emrcontainers_virtual_cluster",
    "data_source/aws_fis_experiment_templates",
    "data_source/aws_fsx_ontap_storage_virtual_machine",
    "data_source/aws_fsx_ontap_storage_virtual_machines",
    "data_source/aws_fsx_openzfs_snapshot",
    "data_source/aws_fsx_windows_file_system",
    "data_source/aws_globalaccelerator_accelerator",
    "data_source/aws_globalaccelerator_custom_routing_accelerator",
    "data_source/aws_glue_catalog_table",
    "data_source/aws_glue_script",
    "data_source/aws_grafana_workspace",
    "data_source/aws_guardduty_detector",
    "data_source/aws_iam_access_keys",
    "data_source/aws_iam_policy",
    "data_source/aws_iam_policy_document",
    "data_source/aws_iam_principal_policy_simulation",
    "data_source/aws_iam_roles",
    "data_source/aws_iam_server_certificate",
    "data_source/aws_iam_users",
    "data_source/aws_identitystore_group",
    "data_source/aws_identitystore_groups",
    "data_source/aws_identitystore_user",
    "data_source/aws_identitystore_users",
    "data_source/aws_imagebuilder_components",
    "data_source/aws_imagebuilder_container_recipe",
    "data_source/aws_imagebuilder_container_recipes",
    "data_source/aws_imagebuilder_distribution_configuration",
    "data_source/aws_imagebuilder_distribution_configurations",
    "data_source/aws_imagebuilder_image",
    "data_source/aws_imagebuilder_image_pipeline",
    "data_source/aws_imagebuilder_image_pipelines",
    "data_source/aws_imagebuilder_image_recipe",
    "data_source/aws_imagebuilder_image_recipes",
    "data_source/aws_imagebuilder_infrastructure_configuration",
    "data_source/aws_imagebuilder_infrastructure_configurations",
    "data_source/aws_instance",
    "data_source/aws_instances",
    "data_source/aws_internet_gateway",
    "data_source/aws_iot_endpoint",
    "data_source/aws_ip_ranges",
    "data_source/aws_kendra_experience",
    "data_source/aws_kendra_faq",
    "data_source/aws_kendra_index",
    "data_source/aws_kendra_query_suggestions_block_list",
    "data_source/aws_kendra_thesaurus",
    "data_source/aws_key_pair",
    "data_source/aws_kinesis_firehose_delivery_stream",
    "data_source/aws_kinesis_stream",
    "data_source/aws_kinesis_stream_consumer",
    "data_source/aws_kms_alias",
    "data_source/aws_kms_custom_key_store",
    "data_source/aws_kms_key",
    "data_source/aws_kms_public_key",
    "data_source/aws_kms_secrets",
    "data_source/aws_lakeformation_permissions",
    "data_source/aws_lambda_function",
    "data_source/aws_lambda_layer_version",
    "data_source/aws_launch_configuration",
    "data_source/aws_launch_template",
    "data_source/aws_lb",
    "data_source/aws_lb_listener",
    "data_source/aws_lb_listener_rule",
    "data_source/aws_lb_target_group",
    "data_source/aws_lbs",
    "data_source/aws_lex_intent",
    "data_source/aws_lex_slot_type",
    "data_source/aws_licensemanager_grants",
    "data_source/aws_licensemanager_received_license",
    "data_source/aws_licensemanager_received_licenses",
    "data_source/aws_location_map",
    "data_source/aws_medialive_input",
    "data_source/aws_memorydb_cluster",
    "data_source/aws_memorydb_parameter_group",
    "data_source/aws_memorydb_snapshot",
    "data_source/aws_memorydb_user",
    "data_source/aws_msk_broker_nodes",
    "data_source/aws_nat_gateway",
    "data_source/aws_nat_gateways",
    "data_source/aws_neptune_engine_version",
    "data_source/aws_network_acls",
    "data_source/aws_network_interface",
    "data_source/aws_network_interfaces",
    "data_source/aws_networkfirewall_firewall",
    "data_source/aws_networkfirewall_firewall_policy",
    "data_source/aws_networkfirewall_resource_policy",
    "data_source/aws_networkmanager_core_network_policy_document",
    "data_source/aws_networkmanager_device",
    "data_source/aws_networkmanager_link",
    "data_source/aws_networkmanager_site",
    "data_source/aws_oam_link",
    "data_source/aws_odb_cloud_exadata_infrastructure",
    "data_source/aws_odb_cloud_vm_cluster",
    "data_source/aws_odb_db_node",
    "data_source/aws_odb_network",
    "data_source/aws_odb_networks",
    "data_source/aws_opensearch_domain",
    "data_source/aws_opensearchserverless_collection",
    "data_source/aws_opensearchserverless_security_config",
    "data_source/aws_organizations_delegated_administrators",
    "data_source/aws_organizations_delegated_services",
    "data_source/aws_organizations_entity_path",
    "data_source/aws_organizations_organization",
    "data_source/aws_organizations_organizational_unit_child_accounts",
    "data_source/aws_organizations_organizational_unit_descendant_accounts",
    "data_source/aws_organizations_organizational_unit_descendant_organizational_units",
    "data_source/aws_organizations_organizational_units",
    "data_source/aws_organizations_resource_tags",
    "data_source/aws_polly_voices",
    "data_source/aws_prefix_list",
    "data_source/aws_pricing_product",
    "data_source/aws_qldb_ledger",
    "data_source/aws_quicksight_analysis",
    "data_source/aws_quicksight_data_set",
    "data_source/aws_quicksight_theme",
    "data_source/aws_quicksight_user",
    "data_source/aws_ram_resource_share",
    "data_source/aws_rds_cluster",
    "data_source/aws_rds_clusters",
    "data_source/aws_rds_engine_version",
    "data_source/aws_rds_global_cluster",
    "data_source/aws_redshift_cluster",
    "data_source/aws_redshiftserverless_workgroup",
    "data_source/aws_regions",
    "data_source/aws_resourcegroupstaggingapi_resources",
    "data_source/aws_route",
    "data_source/aws_route_table",
    "data_source/aws_route_tables",
    "data_source/aws_route53_records",
    "data_source/aws_route53_resolver_endpoint",
    "data_source/aws_route53_resolver_query_log_config",
    "data_source/aws_route53_resolver_rule",
    "data_source/aws_route53_resolver_rules",
    "data_source/aws_route53_traffic_policy_document",
    "data_source/aws_route53_zone",
    "data_source/aws_route53profiles_profiles",
    "data_source/aws_s3_access_point",
    "data_source/aws_s3_bucket_object",
    "data_source/aws_s3_bucket_replication_configuration",
    "data_source/aws_s3_object",
    "data_source/aws_s3control_access_points",
    "data_source/aws_s3control_multi_region_access_point",
    "data_source/aws_s3files_access_point",
    "data_source/aws_s3files_file_systems",
    "data_source/aws_savingsplans_offerings",
    "data_source/aws_savingsplans_savings_plan",
    "data_source/aws_secretsmanager_secret_version",
    "data_source/aws_secretsmanager_secret_versions",
    "data_source/aws_secretsmanager_secrets",
    "data_source/aws_security_group",
    "data_source/aws_security_groups",
    "data_source/aws_securityhub_standards_control_associations",
    "data_source/aws_service",
    "data_source/aws_service_principal",
    "data_source/aws_servicecatalog_constraint",
    "data_source/aws_servicequotas_service_quota",
    "data_source/aws_sesv2_configuration_set",
    "data_source/aws_sesv2_dedicated_ip_pool",
    "data_source/aws_sesv2_email_identity",
    "data_source/aws_sfn_state_machine",
    "data_source/aws_signer_signing_profile",
    "data_source/aws_ssm_document",
    "data_source/aws_ssm_instances",
    "data_source/aws_ssm_maintenance_windows",
    "data_source/aws_ssm_patch_baseline",
    "data_source/aws_ssm_patch_baselines",
    "data_source/aws_ssmcontacts_contact_channel",
    "data_source/aws_ssmincidents_replication_set",
    "data_source/aws_ssmincidents_response_plan",
    "data_source/aws_ssoadmin_permission_set",
    "data_source/aws_ssoadmin_principal_application_assignments",
    "data_source/aws_subnet",
    "data_source/aws_subnets",
    "data_source/aws_synthetics_runtime_versions",
    "data_source/aws_timestreamwrite_database",
    "data_source/aws_timestreamwrite_table",
    "data_source/aws_transfer_connector",
    "data_source/aws_verifiedpermissions_policy_store",
    "data_source/aws_vpc",
    "data_source/aws_vpc_dhcp_options",
    "data_source/aws_vpc_endpoint",
    "data_source/aws_vpc_endpoint_associations",
    "data_source/aws_vpc_endpoint_service",
    "data_source/aws_vpc_ipam_pool",
    "data_source/aws_vpc_ipam_pool_cidrs",
    "data_source/aws_vpc_ipam_pools",
    "data_source/aws_vpc_ipams",
    "data_source/aws_vpc_peering_connection",
    "data_source/aws_vpc_peering_connections",
    "data_source/aws_vpc_security_group_rule",
    "data_source/aws_vpc_security_group_rules",
    "data_source/aws_vpclattice_service",
    "data_source/aws_vpclattice_service_network",
    "data_source/aws_vpcs",
    "data_source/aws_vpn_connection",
    "data_source/aws_vpn_gateway",
    "data_source/aws_waf_subscribed_rule_group",
    "data_source/aws_wafregional_subscribed_rule_group",
    "data_source/aws_wafv2_regex_pattern_set",
    "data_source/aws_workspaces_directory",
    "data_source/aws_workspaces_image",
    "data_source/aws_workspaces_workspace",
    "ephemeral/aws_cognito_identity_openid_token_for_developer_identity",
    "ephemeral/aws_ecr_authorization_token",
    "ephemeral/aws_ecrpublic_authorization_token",
    "ephemeral/aws_eks_cluster_auth",
    "ephemeral/aws_kms_secrets",
    "ephemeral/aws_secretsmanager_random_password",
    "ephemeral/aws_secretsmanager_secret_version",
    "ephemeral/aws_ssm_parameter",
    "ephemeral/aws_sts_web_identity_token",
    "list_resource/aws_batch_job_queue",
    "list_resource/aws_cloudwatch_log_group",
    "list_resource/aws_cloudwatch_log_metric_filter",
    "list_resource/aws_ebs_volume",
    "list_resource/aws_ec2_secondary_subnet",
    "list_resource/aws_iam_policy",
    "list_resource/aws_iam_user",
    "list_resource/aws_instance",
    "list_resource/aws_internet_gateway",
    "list_resource/aws_nat_gateway",
    "list_resource/aws_route_table",
    "list_resource/aws_s3_object",
    "list_resource/aws_s3files_access_point",
    "list_resource/aws_s3files_mount_target",
    "list_resource/aws_s3files_synchronization_configuration",
    "list_resource/aws_security_group",
    "list_resource/aws_ssm_association",
    "list_resource/aws_subnet",
    "list_resource/aws_vpc",
    "list_resource/aws_vpc_endpoint",
    "list_resource/aws_vpc_security_group_egress_rule",
    "resource/aws_accessanalyzer_analyzer",
    "resource/aws_accessanalyzer_archive_rule",
    "resource/aws_acm_certificate",
    "resource/aws_acmpca_certificate",
    "resource/aws_acmpca_certificate_authority",
    "resource/aws_ami",
    "resource/aws_ami_copy",
    "resource/aws_ami_from_instance",
    "resource/aws_amplify_app",
    "resource/aws_amplify_domain_association",
    "resource/aws_api_gateway_account",
    "resource/aws_api_gateway_authorizer",
    "resource/aws_api_gateway_documentation_part",
    "resource/aws_api_gateway_domain_name",
    "resource/aws_api_gateway_integration",
    "resource/aws_api_gateway_method",
    "resource/aws_api_gateway_method_response",
    "resource/aws_api_gateway_method_settings",
    "resource/aws_api_gateway_rest_api",
    "resource/aws_api_gateway_rest_api_put",
    "resource/aws_api_gateway_stage",
    "resource/aws_api_gateway_usage_plan",
    "resource/aws_api_gateway_vpc_link",
    "resource/aws_apigatewayv2_api",
    "resource/aws_apigatewayv2_authorizer",
    "resource/aws_apigatewayv2_domain_name",
    "resource/aws_apigatewayv2_integration",
    "resource/aws_apigatewayv2_route",
    "resource/aws_apigatewayv2_routing_rule",
    "resource/aws_apigatewayv2_stage",
    "resource/aws_app_cookie_stickiness_policy",
    "resource/aws_appautoscaling_policy",
    "resource/aws_appautoscaling_scheduled_action",
    "resource/aws_appautoscaling_target",
    "resource/aws_appconfig_configuration_profile",
    "resource/aws_appconfig_environment",
    "resource/aws_appconfig_extension",
    "resource/aws_appfabric_app_authorization",
    "resource/aws_appfabric_app_authorization_connection",
    "resource/aws_appfabric_ingestion",
    "resource/aws_appfabric_ingestion_destination",
    "resource/aws_appflow_connector_profile",
    "resource/aws_appflow_flow",
    "resource/aws_appintegrations_data_integration",
    "resource/aws_appintegrations_event_integration",
    "resource/aws_apprunner_auto_scaling_configuration_version",
    "resource/aws_apprunner_custom_domain_association",
    "resource/aws_apprunner_observability_configuration",
    "resource/aws_apprunner_service",
    "resource/aws_apprunner_vpc_connector",
    "resource/aws_apprunner_vpc_ingress_connection",
    "resource/aws_appstream_directory_config",
    "resource/aws_appstream_fleet",
    "resource/aws_appstream_fleet_stack_association",
    "resource/aws_appstream_image_builder",
    "resource/aws_appstream_stack",
    "resource/aws_appstream_user",
    "resource/aws_appstream_user_stack_association",
    "resource/aws_appsync_api",
    "resource/aws_appsync_api_key",
    "resource/aws_appsync_channel_namespace",
    "resource/aws_appsync_datasource",
    "resource/aws_appsync_graphql_api",
    "resource/aws_appsync_resolver",
    "resource/aws_appsync_source_api_association",
    "resource/aws_arcregionswitch_plan",
    "resource/aws_arczonalshift_zonal_autoshift_configuration",
    "resource/aws_athena_database",
    "resource/aws_athena_workgroup",
    "resource/aws_auditmanager_assessment",
    "resource/aws_auditmanager_control",
    "resource/aws_autoscaling_group",
    "resource/aws_autoscaling_group_tag",
    "resource/aws_autoscaling_notification",
    "resource/aws_autoscaling_policy",
    "resource/aws_autoscaling_traffic_source_attachment",
    "resource/aws_autoscalingplans_scaling_plan",
    "resource/aws_backup_framework",
    "resource/aws_backup_logically_air_gapped_vault",
    "resource/aws_backup_plan",
    "resource/aws_backup_report_plan",
    "resource/aws_backup_restore_testing_plan",
    "resource/aws_backup_restore_testing_selection",
    "resource/aws_backup_selection",
    "resource/aws_batch_compute_environment",
    "resource/aws_batch_job_definition",
    "resource/aws_batch_job_queue",
    "resource/aws_batch_scheduling_policy",
    "resource/aws_bcmdataexports_export",
    "resource/aws_bedrock_custom_model",
    "resource/aws_bedrock_guardrail",
    "resource/aws_bedrock_inference_profile",
    "resource/aws_bedrockagent_agent",
    "resource/aws_bedrockagent_agent_action_group",
    "resource/aws_bedrockagent_agent_collaborator",
    "resource/aws_bedrockagent_data_source",
    "resource/aws_bedrockagent_flow",
    "resource/aws_bedrockagent_knowledge_base",
    "resource/aws_bedrockagent_prompt",
    "resource/aws_bedrockagentcore_agent_runtime",
    "resource/aws_bedrockagentcore_api_key_credential_provider",
    "resource/aws_bedrockagentcore_browser",
    "resource/aws_bedrockagentcore_code_interpreter",
    "resource/aws_bedrockagentcore_gateway",
    "resource/aws_bedrockagentcore_gateway_target",
    "resource/aws_bedrockagentcore_memory_strategy",
    "resource/aws_bedrockagentcore_oauth2_credential_provider",
    "resource/aws_bedrockagentcore_token_vault_cmk",
    "resource/aws_billing_view",
    "resource/aws_budgets_budget",
    "resource/aws_budgets_budget_action",
    "resource/aws_ce_anomaly_subscription",
    "resource/aws_ce_cost_category",
    "resource/aws_chime_voice_connector_group",
    "resource/aws_chime_voice_connector_origination",
    "resource/aws_chime_voice_connector_streaming",
    "resource/aws_chime_voice_connector_termination_credentials",
    "resource/aws_chimesdkmediapipelines_media_insights_pipeline_configuration",
    "resource/aws_chimesdkvoice_global_settings",
    "resource/aws_chimesdkvoice_sip_media_application",
    "resource/aws_chimesdkvoice_sip_rule",
    "resource/aws_chimesdkvoice_voice_profile_domain",
    "resource/aws_cleanrooms_collaboration",
    "resource/aws_cleanrooms_configured_table",
    "resource/aws_cleanrooms_membership",
    "resource/aws_cloud9_environment_ec2",
    "resource/aws_cloudformation_stack",
    "resource/aws_cloudformation_stack_instances",
    "resource/aws_cloudformation_stack_set",
    "resource/aws_cloudformation_stack_set_instance",
    "resource/aws_cloudformation_type",
    "resource/aws_cloudfront_cache_policy",
    "resource/aws_cloudfront_connection_function",
    "resource/aws_cloudfront_connection_group",
    "resource/aws_cloudfront_continuous_deployment_policy",
    "resource/aws_cloudfront_distribution",
    "resource/aws_cloudfront_distribution_tenant",
    "resource/aws_cloudfront_field_level_encryption_config",
    "resource/aws_cloudfront_field_level_encryption_profile",
    "resource/aws_cloudfront_key_value_store",
    "resource/aws_cloudfront_monitoring_subscription",
    "resource/aws_cloudfront_multitenant_distribution",
    "resource/aws_cloudfront_origin_access_identity",
    "resource/aws_cloudfront_origin_request_policy",
    "resource/aws_cloudfront_public_key",
    "resource/aws_cloudfront_realtime_log_config",
    "resource/aws_cloudfront_response_headers_policy",
    "resource/aws_cloudfront_trust_store",
    "resource/aws_cloudfront_vpc_origin",
    "resource/aws_cloudfrontkeyvaluestore_keys_exclusive",
    "resource/aws_cloudhsm_v2_cluster",
    "resource/aws_cloudsearch_domain",
    "resource/aws_cloudtrail",
    "resource/aws_cloudtrail_event_data_store",
    "resource/aws_cloudwatch_alarm_mute_rule",
    "resource/aws_cloudwatch_composite_alarm",
    "resource/aws_cloudwatch_contributor_insight_rule",
    "resource/aws_cloudwatch_contributor_managed_insight_rule",
    "resource/aws_cloudwatch_event_bus",
    "resource/aws_cloudwatch_event_bus_policy",
    "resource/aws_cloudwatch_event_connection",
    "resource/aws_cloudwatch_event_endpoint",
    "resource/aws_cloudwatch_event_permission",
    "resource/aws_cloudwatch_event_rule",
    "resource/aws_cloudwatch_event_target",
    "resource/aws_cloudwatch_log_anomaly_detector",
    "resource/aws_cloudwatch_log_delivery",
    "resource/aws_cloudwatch_log_delivery_destination",
    "resource/aws_cloudwatch_log_group",
    "resource/aws_cloudwatch_log_metric_filter",
    "resource/aws_cloudwatch_log_transformer",
    "resource/aws_cloudwatch_metric_alarm",
    "resource/aws_cloudwatch_metric_stream",
    "resource/aws_codeartifact_repository",
    "resource/aws_codebuild_fleet",
    "resource/aws_codebuild_project",
    "resource/aws_codebuild_report_group",
    "resource/aws_codebuild_source_credential",
    "resource/aws_codebuild_webhook",
    "resource/aws_codecatalyst_dev_environment",
    "resource/aws_codecommit_trigger",
    "resource/aws_codeconnections_connection",
    "resource/aws_codeconnections_host",
    "resource/aws_codedeploy_deployment_config",
    "resource/aws_codedeploy_deployment_group",
    "resource/aws_codeguruprofiler_profiling_group",
    "resource/aws_codegurureviewer_repository_association",
    "resource/aws_codepipeline",
    "resource/aws_codepipeline_custom_action_type",
    "resource/aws_codepipeline_webhook",
    "resource/aws_codestarconnections_host",
    "resource/aws_codestarnotifications_notification_rule",
    "resource/aws_cognito_identity_pool",
    "resource/aws_cognito_identity_pool_provider_principal_tag",
    "resource/aws_cognito_identity_pool_roles_attachment",
    "resource/aws_cognito_identity_provider",
    "resource/aws_cognito_log_delivery_configuration",
    "resource/aws_cognito_managed_login_branding",
    "resource/aws_cognito_managed_user_pool_client",
    "resource/aws_cognito_resource_server",
    "resource/aws_cognito_risk_configuration",
    "resource/aws_cognito_user",
    "resource/aws_cognito_user_pool",
    "resource/aws_cognito_user_pool_client",
    "resource/aws_cognito_user_pool_ui_customization",
    "resource/aws_comprehend_document_classifier",
    "resource/aws_comprehend_entity_recognizer",
    "resource/aws_computeoptimizer_recommendation_preferences",
    "resource/aws_config_config_rule",
    "resource/aws_config_configuration_aggregator",
    "resource/aws_config_configuration_recorder",
    "resource/aws_config_conformance_pack",
    "resource/aws_config_delivery_channel",
    "resource/aws_config_organization_conformance_pack",
    "resource/aws_config_remediation_configuration",
    "resource/aws_connect_bot_association",
    "resource/aws_connect_hours_of_operation",
    "resource/aws_connect_instance",
    "resource/aws_connect_instance_storage_config",
    "resource/aws_connect_queue",
    "resource/aws_connect_quick_connect",
    "resource/aws_connect_routing_profile",
    "resource/aws_connect_security_profile",
    "resource/aws_connect_user",
    "resource/aws_connect_user_hierarchy_group",
    "resource/aws_connect_user_hierarchy_structure",
    "resource/aws_connect_vocabulary",
    "resource/aws_controltower_baseline",
    "resource/aws_controltower_control",
    "resource/aws_controltower_landing_zone",
    "resource/aws_customer_gateway",
    "resource/aws_customerprofiles_domain",
    "resource/aws_customerprofiles_profile",
    "resource/aws_dataexchange_event_action",
    "resource/aws_dataexchange_revision_assets",
    "resource/aws_datapipeline_pipeline_definition",
    "resource/aws_datasync_location_azure_blob",
    "resource/aws_datasync_location_efs",
    "resource/aws_datasync_location_fsx_ontap_file_system",
    "resource/aws_datasync_location_fsx_openzfs_file_system",
    "resource/aws_datasync_location_hdfs",
    "resource/aws_datasync_location_nfs",
    "resource/aws_datasync_location_s3",
    "resource/aws_datasync_location_smb",
    "resource/aws_datasync_task",
    "resource/aws_datazone_asset_type",
    "resource/aws_datazone_domain",
    "resource/aws_datazone_environment",
    "resource/aws_datazone_environment_blueprint_configuration",
    "resource/aws_datazone_environment_profile",
    "resource/aws_datazone_form_type",
    "resource/aws_datazone_glossary",
    "resource/aws_datazone_glossary_term",
    "resource/aws_datazone_project",
    "resource/aws_dax_cluster",
    "resource/aws_dax_parameter_group",
    "resource/aws_db_cluster_snapshot",
    "resource/aws_db_instance",
    "resource/aws_db_parameter_group",
    "resource/aws_db_proxy",
    "resource/aws_db_proxy_default_target_group",
    "resource/aws_db_proxy_target",
    "resource/aws_db_snapshot",
    "resource/aws_db_snapshot_copy",
    "resource/aws_default_network_acl",
    "resource/aws_default_route_table",
    "resource/aws_default_security_group",
    "resource/aws_default_subnet",
    "resource/aws_default_vpc",
    "resource/aws_default_vpc_dhcp_options",
    "resource/aws_detective_graph",
    "resource/aws_detective_member",
    "resource/aws_devicefarm_device_pool",
    "resource/aws_devicefarm_project",
    "resource/aws_devicefarm_test_grid_project",
    "resource/aws_devopsguru_event_sources_config",
    "resource/aws_devopsguru_notification_channel",
    "resource/aws_devopsguru_resource_collection",
    "resource/aws_devopsguru_service_integration",
    "resource/aws_directory_service_directory",
    "resource/aws_directory_service_region",
    "resource/aws_directory_service_shared_directory",
    "resource/aws_directory_service_trust",
    "resource/aws_dlm_lifecycle_policy",
    "resource/aws_dms_endpoint",
    "resource/aws_dms_replication_config",
    "resource/aws_dms_replication_instance",
    "resource/aws_dms_replication_subnet_group",
    "resource/aws_docdb_cluster",
    "resource/aws_docdb_cluster_instance",
    "resource/aws_docdb_cluster_parameter_group",
    "resource/aws_docdb_cluster_snapshot",
    "resource/aws_docdb_event_subscription",
    "resource/aws_docdb_global_cluster",
    "resource/aws_docdbelastic_cluster",
    "resource/aws_drs_replication_configuration_template",
    "resource/aws_dsql_cluster",
    "resource/aws_dx_bgp_peer",
    "resource/aws_dx_gateway_association",
    "resource/aws_dx_hosted_private_virtual_interface",
    "resource/aws_dx_hosted_public_virtual_interface",
    "resource/aws_dx_hosted_transit_virtual_interface",
    "resource/aws_dx_lag",
    "resource/aws_dx_private_virtual_interface",
    "resource/aws_dx_public_virtual_interface",
    "resource/aws_dx_transit_virtual_interface",
    "resource/aws_dynamodb_global_secondary_index",
    "resource/aws_dynamodb_global_table",
    "resource/aws_dynamodb_table",
    "resource/aws_dynamodb_table_export",
    "resource/aws_ebs_snapshot_copy",
    "resource/aws_ebs_snapshot_import",
    "resource/aws_ebs_volume",
    "resource/aws_ec2_allowed_images_settings",
    "resource/aws_ec2_client_vpn_endpoint",
    "resource/aws_ec2_default_credit_specification",
    "resource/aws_ec2_fleet",
    "resource/aws_ec2_instance_metadata_defaults",
    "resource/aws_ec2_local_gateway_route_table_vpc_association",
    "resource/aws_ec2_managed_prefix_list",
    "resource/aws_ec2_network_insights_access_scope",
    "resource/aws_ec2_network_insights_analysis",
    "resource/aws_ec2_network_insights_path",
    "resource/aws_ec2_secondary_network",
    "resource/aws_ec2_secondary_subnet",
    "resource/aws_ec2_traffic_mirror_filter_rule",
    "resource/aws_ec2_traffic_mirror_target",
    "resource/aws_ec2_transit_gateway_default_route_table_association",
    "resource/aws_ec2_transit_gateway_default_route_table_propagation",
    "resource/aws_ec2_transit_gateway_metering_policy_entry",
    "resource/aws_ec2_transit_gateway_peering_attachment",
    "resource/aws_ec2_transit_gateway_peering_attachment_accepter",
    "resource/aws_ec2_transit_gateway_prefix_list_reference",
    "resource/aws_ecr_account_setting",
    "resource/aws_ecr_registry_scanning_configuration",
    "resource/aws_ecr_replication_configuration",
    "resource/aws_ecr_repository",
    "resource/aws_ecr_repository_creation_template",
    "resource/aws_ecrpublic_repository",
    "resource/aws_ecs_account_setting_default",
    "resource/aws_ecs_capacity_provider",
    "resource/aws_ecs_cluster",
    "resource/aws_ecs_cluster_capacity_providers",
    "resource/aws_ecs_express_gateway_service",
    "resource/aws_ecs_service",
    "resource/aws_ecs_task_definition",
    "resource/aws_ecs_task_set",
    "resource/aws_efs_access_point",
    "resource/aws_efs_backup_policy",
    "resource/aws_efs_file_system",
    "resource/aws_efs_mount_target",
    "resource/aws_efs_replication_configuration",
    "resource/aws_eip",
    "resource/aws_eip_association",
    "resource/aws_eks_access_entry",
    "resource/aws_eks_access_policy_association",
    "resource/aws_eks_addon",
    "resource/aws_eks_capability",
    "resource/aws_eks_cluster",
    "resource/aws_eks_fargate_profile",
    "resource/aws_eks_identity_provider_config",
    "resource/aws_eks_node_group",
    "resource/aws_elastic_beanstalk_application",
    "resource/aws_elastic_beanstalk_configuration_template",
    "resource/aws_elastic_beanstalk_environment",
    "resource/aws_elasticache_cluster",
    "resource/aws_elasticache_global_replication_group",
    "resource/aws_elasticache_parameter_group",
    "resource/aws_elasticache_replication_group",
    "resource/aws_elasticache_reserved_cache_node",
    "resource/aws_elasticache_serverless_cache",
    "resource/aws_elasticache_subnet_group",
    "resource/aws_elasticache_user",
    "resource/aws_elasticsearch_domain",
    "resource/aws_elasticsearch_domain_saml_options",
    "resource/aws_elasticsearch_vpc_endpoint",
    "resource/aws_elastictranscoder_pipeline",
    "resource/aws_elastictranscoder_preset",
    "resource/aws_elb",
    "resource/aws_emr_block_public_access_configuration",
    "resource/aws_emr_cluster",
    "resource/aws_emr_instance_fleet",
    "resource/aws_emr_instance_group",
    "resource/aws_emr_managed_scaling_policy",
    "resource/aws_emr_security_configuration",
    "resource/aws_emr_studio",
    "resource/aws_emr_studio_session_mapping",
    "resource/aws_emrcontainers_job_template",
    "resource/aws_emrcontainers_virtual_cluster",
    "resource/aws_emrserverless_application",
    "resource/aws_evidently_feature",
    "resource/aws_evidently_launch",
    "resource/aws_evidently_project",
    "resource/aws_finspace_kx_cluster",
    "resource/aws_finspace_kx_dataview",
    "resource/aws_finspace_kx_environment",
    "resource/aws_finspace_kx_scaling_group",
    "resource/aws_finspace_kx_volume",
    "resource/aws_fis_experiment_template",
    "resource/aws_flow_log",
    "resource/aws_fms_policy",
    "resource/aws_fms_resource_set",
    "resource/aws_fsx_backup",
    "resource/aws_fsx_data_repository_association",
    "resource/aws_fsx_file_cache",
    "resource/aws_fsx_ontap_file_system",
    "resource/aws_fsx_ontap_storage_virtual_machine",
    "resource/aws_fsx_openzfs_file_system",
    "resource/aws_fsx_openzfs_snapshot",
    "resource/aws_fsx_openzfs_volume",
    "resource/aws_gamelift_alias",
    "resource/aws_gamelift_build",
    "resource/aws_gamelift_fleet",
    "resource/aws_gamelift_game_server_group",
    "resource/aws_gamelift_game_session_queue",
    "resource/aws_gamelift_script",
    "resource/aws_glacier_vault",
    "resource/aws_globalaccelerator_accelerator",
    "resource/aws_globalaccelerator_cross_account_attachment",
    "resource/aws_globalaccelerator_custom_routing_accelerator",
    "resource/aws_globalaccelerator_custom_routing_endpoint_group",
    "resource/aws_globalaccelerator_custom_routing_listener",
    "resource/aws_globalaccelerator_endpoint_group",
    "resource/aws_globalaccelerator_listener",
    "resource/aws_glue_catalog",
    "resource/aws_glue_catalog_database",
    "resource/aws_glue_catalog_table",
    "resource/aws_glue_catalog_table_optimizer",
    "resource/aws_glue_classifier",
    "resource/aws_glue_connection",
    "resource/aws_glue_crawler",
    "resource/aws_glue_data_catalog_encryption_settings",
    "resource/aws_glue_data_quality_ruleset",
    "resource/aws_glue_job",
    "resource/aws_glue_ml_transform",
    "resource/aws_glue_partition",
    "resource/aws_glue_partition_index",
    "resource/aws_glue_security_configuration",
    "resource/aws_glue_trigger",
    "resource/aws_glue_user_defined_function",
    "resource/aws_grafana_workspace",
    "resource/aws_guardduty_detector",
    "resource/aws_guardduty_detector_feature",
    "resource/aws_guardduty_filter",
    "resource/aws_guardduty_malware_protection_plan",
    "resource/aws_guardduty_member_detector_feature",
    "resource/aws_guardduty_organization_configuration",
    "resource/aws_guardduty_organization_configuration_feature",
    "resource/aws_guardduty_publishing_destination",
    "resource/aws_iam_group_membership",
    "resource/aws_iam_group_policy",
    "resource/aws_iam_group_policy_attachment",
    "resource/aws_iam_policy_attachment",
    "resource/aws_iam_role",
    "resource/aws_iam_role_policy",
    "resource/aws_iam_role_policy_attachment",
    "resource/aws_iam_server_certificate",
    "resource/aws_iam_service_linked_role",
    "resource/aws_iam_user",
    "resource/aws_iam_user_policy_attachment",
    "resource/aws_identitystore_user",
    "resource/aws_imagebuilder_component",
    "resource/aws_imagebuilder_container_recipe",
    "resource/aws_imagebuilder_distribution_configuration",
    "resource/aws_imagebuilder_image",
    "resource/aws_imagebuilder_image_pipeline",
    "resource/aws_imagebuilder_image_recipe",
    "resource/aws_imagebuilder_infrastructure_configuration",
    "resource/aws_imagebuilder_lifecycle_policy",
    "resource/aws_inspector_assessment_target",
    "resource/aws_inspector_assessment_template",
    "resource/aws_inspector2_enabler",
    "resource/aws_inspector2_filter",
    "resource/aws_inspector2_organization_configuration",
    "resource/aws_instance",
    "resource/aws_internet_gateway",
    "resource/aws_internetmonitor_monitor",
    "resource/aws_invoicing_invoice_unit",
    "resource/aws_iot_billing_group",
    "resource/aws_iot_ca_certificate",
    "resource/aws_iot_certificate",
    "resource/aws_iot_indexing_configuration",
    "resource/aws_iot_provisioning_template",
    "resource/aws_iot_thing_group",
    "resource/aws_iot_thing_type",
    "resource/aws_iot_topic_rule",
    "resource/aws_iot_topic_rule_destination",
    "resource/aws_ivs_recording_configuration",
    "resource/aws_ivschat_logging_configuration",
    "resource/aws_ivschat_room",
    "resource/aws_kendra_data_source",
    "resource/aws_kendra_experience",
    "resource/aws_kendra_faq",
    "resource/aws_kendra_index",
    "resource/aws_kendra_query_suggestions_block_list",
    "resource/aws_kendra_thesaurus",
    "resource/aws_keyspaces_keyspace",
    "resource/aws_keyspaces_table",
    "resource/aws_kinesis_analytics_application",
    "resource/aws_kinesis_firehose_delivery_stream",
    "resource/aws_kinesis_stream",
    "resource/aws_kinesis_stream_consumer",
    "resource/aws_kinesis_video_stream",
    "resource/aws_kinesisanalyticsv2_application",
    "resource/aws_kms_alias",
    "resource/aws_kms_ciphertext",
    "resource/aws_kms_custom_key_store",
    "resource/aws_kms_grant",
    "resource/aws_kms_key",
    "resource/aws_kms_key_policy",
    "resource/aws_kms_replica_external_key",
    "resource/aws_kms_replica_key",
    "resource/aws_lakeformation_data_cells_filter",
    "resource/aws_lakeformation_data_lake_settings",
    "resource/aws_lakeformation_identity_center_configuration",
    "resource/aws_lakeformation_lf_tag_expression",
    "resource/aws_lakeformation_opt_in",
    "resource/aws_lakeformation_permissions",
    "resource/aws_lakeformation_resource",
    "resource/aws_lakeformation_resource_lf_tag",
    "resource/aws_lakeformation_resource_lf_tags",
    "resource/aws_lambda_alias",
    "resource/aws_lambda_capacity_provider",
    "resource/aws_lambda_code_signing_config",
    "resource/aws_lambda_event_source_mapping",
    "resource/aws_lambda_function",
    "resource/aws_lambda_function_event_invoke_config",
    "resource/aws_lambda_function_url",
    "resource/aws_lambda_permission",
    "resource/aws_launch_configuration",
    "resource/aws_launch_template",
    "resource/aws_lb",
    "resource/aws_lb_cookie_stickiness_policy",
    "resource/aws_lb_listener",
    "resource/aws_lb_listener_rule",
    "resource/aws_lb_ssl_negotiation_policy",
    "resource/aws_lb_target_group",
    "resource/aws_lb_target_group_attachment",
    "resource/aws_lex_bot",
    "resource/aws_lex_bot_alias",
    "resource/aws_lex_intent",
    "resource/aws_lex_slot_type",
    "resource/aws_lexv2models_bot",
    "resource/aws_lexv2models_bot_locale",
    "resource/aws_lexv2models_bot_version",
    "resource/aws_lexv2models_intent",
    "resource/aws_lexv2models_slot",
    "resource/aws_lexv2models_slot_type",
    "resource/aws_licensemanager_grant",
    "resource/aws_licensemanager_grant_accepter",
    "resource/aws_lightsail_certificate",
    "resource/aws_lightsail_container_service",
    "resource/aws_lightsail_container_service_deployment_version",
    "resource/aws_lightsail_database",
    "resource/aws_lightsail_distribution",
    "resource/aws_lightsail_instance",
    "resource/aws_load_balancer_policy",
    "resource/aws_location_map",
    "resource/aws_location_place_index",
    "resource/aws_m2_application",
    "resource/aws_m2_deployment",
    "resource/aws_m2_environment",
    "resource/aws_macie2_account",
    "resource/aws_macie2_classification_export_configuration",
    "resource/aws_macie2_classification_job",
    "resource/aws_macie2_custom_data_identifier",
    "resource/aws_macie2_findings_filter",
    "resource/aws_macie2_member",
    "resource/aws_main_route_table_association",
    "resource/aws_media_convert_queue",
    "resource/aws_media_package_channel",
    "resource/aws_medialive_channel",
    "resource/aws_medialive_input",
    "resource/aws_medialive_input_security_group",
    "resource/aws_medialive_multiplex",
    "resource/aws_medialive_multiplex_program",
    "resource/aws_memorydb_cluster",
    "resource/aws_memorydb_multi_region_cluster",
    "resource/aws_memorydb_parameter_group",
    "resource/aws_memorydb_snapshot",
    "resource/aws_memorydb_user",
    "resource/aws_mq_broker",
    "resource/aws_msk_cluster",
    "resource/aws_msk_cluster_policy",
    "resource/aws_msk_replicator",
    "resource/aws_msk_serverless_cluster",
    "resource/aws_msk_single_scram_secret_association",
    "resource/aws_mwaa_environment",
    "resource/aws_nat_gateway",
    "resource/aws_nat_gateway_eip_association",
    "resource/aws_neptune_cluster",
    "resource/aws_neptune_cluster_instance",
    "resource/aws_neptune_cluster_parameter_group",
    "resource/aws_neptune_cluster_snapshot",
    "resource/aws_neptune_global_cluster",
    "resource/aws_neptune_parameter_group",
    "resource/aws_neptunegraph_graph",
    "resource/aws_network_acl",
    "resource/aws_network_interface",
    "resource/aws_networkfirewall_firewall",
    "resource/aws_networkfirewall_firewall_policy",
    "resource/aws_networkfirewall_logging_configuration",
    "resource/aws_networkfirewall_rule_group",
    "resource/aws_networkfirewall_tls_inspection_configuration",
    "resource/aws_networkfirewall_vpc_endpoint_association",
    "resource/aws_networkflowmonitor_monitor",
    "resource/aws_networkflowmonitor_scope",
    "resource/aws_networkmanager_connect_attachment",
    "resource/aws_networkmanager_connect_peer",
    "resource/aws_networkmanager_core_network",
    "resource/aws_networkmanager_device",
    "resource/aws_networkmanager_link",
    "resource/aws_networkmanager_site",
    "resource/aws_networkmanager_vpc_attachment",
    "resource/aws_networkmonitor_probe",
    "resource/aws_notifications_event_rule",
    "resource/aws_notifications_notification_configuration",
    "resource/aws_notifications_notification_hub",
    "resource/aws_notificationscontacts_email_contact",
    "resource/aws_observabilityadmin_centralization_rule_for_organization",
    "resource/aws_observabilityadmin_telemetry_pipeline",
    "resource/aws_observabilityadmin_telemetry_rule",
    "resource/aws_odb_cloud_autonomous_vm_cluster",
    "resource/aws_odb_cloud_exadata_infrastructure",
    "resource/aws_odb_cloud_vm_cluster",
    "resource/aws_odb_network",
    "resource/aws_odb_network_peering_connection",
    "resource/aws_opensearch_application",
    "resource/aws_opensearch_domain",
    "resource/aws_opensearch_domain_saml_options",
    "resource/aws_opensearch_outbound_connection",
    "resource/aws_opensearch_package",
    "resource/aws_opensearch_package_association",
    "resource/aws_opensearch_vpc_endpoint",
    "resource/aws_opensearchserverless_security_config",
    "resource/aws_organizations_organization",
    "resource/aws_organizations_organizational_unit",
    "resource/aws_organizations_policy",
    "resource/aws_osis_pipeline",
    "resource/aws_outposts_capacity_task",
    "resource/aws_paymentcryptography_key",
    "resource/aws_pinpoint_apns_channel",
    "resource/aws_pinpoint_apns_sandbox_channel",
    "resource/aws_pinpoint_apns_voip_channel",
    "resource/aws_pinpoint_apns_voip_sandbox_channel",
    "resource/aws_pinpoint_app",
    "resource/aws_pinpoint_email_template",
    "resource/aws_pinpoint_gcm_channel",
    "resource/aws_pinpointsmsvoicev2_phone_number",
    "resource/aws_pipes_pipe",
    "resource/aws_placement_group",
    "resource/aws_prometheus_query_logging_configuration",
    "resource/aws_prometheus_resource_policy",
    "resource/aws_prometheus_scraper",
    "resource/aws_prometheus_workspace",
    "resource/aws_prometheus_workspace_configuration",
    "resource/aws_proxy_protocol_policy",
    "resource/aws_qbusiness_application",
    "resource/aws_qldb_stream",
    "resource/aws_quicksight_analysis",
    "resource/aws_quicksight_custom_permissions",
    "resource/aws_quicksight_dashboard",
    "resource/aws_quicksight_data_set",
    "resource/aws_quicksight_data_source",
    "resource/aws_quicksight_folder",
    "resource/aws_quicksight_group_membership",
    "resource/aws_quicksight_iam_policy_assignment",
    "resource/aws_quicksight_key_registration",
    "resource/aws_quicksight_refresh_schedule",
    "resource/aws_quicksight_template",
    "resource/aws_quicksight_theme",
    "resource/aws_ram_permission",
    "resource/aws_ram_resource_share_associations_exclusive",
    "resource/aws_rbin_rule",
    "resource/aws_rds_cluster",
    "resource/aws_rds_cluster_activity_stream",
    "resource/aws_rds_cluster_endpoint",
    "resource/aws_rds_cluster_instance",
    "resource/aws_rds_cluster_parameter_group",
    "resource/aws_rds_cluster_snapshot_copy",
    "resource/aws_rds_global_cluster",
    "resource/aws_rds_integration",
    "resource/aws_rds_shard_group",
    "resource/aws_redshift_cluster",
    "resource/aws_redshift_event_subscription",
    "resource/aws_redshift_hsm_configuration",
    "resource/aws_redshift_idc_application",
    "resource/aws_redshift_integration",
    "resource/aws_redshift_parameter_group",
    "resource/aws_redshift_partner",
    "resource/aws_redshift_scheduled_action",
    "resource/aws_redshift_snapshot_schedule",
    "resource/aws_redshiftdata_statement",
    "resource/aws_redshiftserverless_namespace",
    "resource/aws_redshiftserverless_workgroup",
    "resource/aws_rekognition_stream_processor",
    "resource/aws_resiliencehub_resiliency_policy",
    "resource/aws_resourceexplorer2_view",
    "resource/aws_resourcegroups_group",
    "resource/aws_rolesanywhere_trust_anchor",
    "resource/aws_route",
    "resource/aws_route_table",
    "resource/aws_route53_delegation_set",
    "resource/aws_route53_health_check",
    "resource/aws_route53_record",
    "resource/aws_route53_records_exclusive",
    "resource/aws_route53_resolver_endpoint",
    "resource/aws_route53_resolver_firewall_rule",
    "resource/aws_route53_resolver_query_log_config",
    "resource/aws_route53_resolver_rule",
    "resource/aws_route53_zone",
    "resource/aws_route53domains_delegation_signer_record",
    "resource/aws_route53domains_domain",
    "resource/aws_route53domains_registered_domain",
    "resource/aws_route53profiles_association",
    "resource/aws_route53profiles_profile",
    "resource/aws_route53profiles_resource_association",
    "resource/aws_route53recoverycontrolconfig_safety_rule",
    "resource/aws_route53recoveryreadiness_resource_set",
    "resource/aws_rum_app_monitor",
    "resource/aws_s3_access_point",
    "resource/aws_s3_account_public_access_block",
    "resource/aws_s3_bucket",
    "resource/aws_s3_bucket_abac",
    "resource/aws_s3_bucket_acl",
    "resource/aws_s3_bucket_analytics_configuration",
    "resource/aws_s3_bucket_cors_configuration",
    "resource/aws_s3_bucket_intelligent_tiering_configuration",
    "resource/aws_s3_bucket_inventory",
    "resource/aws_s3_bucket_lifecycle_configuration",
    "resource/aws_s3_bucket_logging",
    "resource/aws_s3_bucket_metadata_configuration",
    "resource/aws_s3_bucket_metric",
    "resource/aws_s3_bucket_notification",
    "resource/aws_s3_bucket_object",
    "resource/aws_s3_bucket_object_lock_configuration",
    "resource/aws_s3_bucket_ownership_controls",
    "resource/aws_s3_bucket_public_access_block",
    "resource/aws_s3_bucket_replication_configuration",
    "resource/aws_s3_bucket_server_side_encryption_configuration",
    "resource/aws_s3_bucket_versioning",
    "resource/aws_s3_bucket_website_configuration",
    "resource/aws_s3_directory_bucket",
    "resource/aws_s3_object",
    "resource/aws_s3_object_copy",
    "resource/aws_s3control_access_grant",
    "resource/aws_s3control_access_grants_location",
    "resource/aws_s3control_bucket_lifecycle_configuration",
    "resource/aws_s3control_directory_bucket_access_point_scope",
    "resource/aws_s3control_multi_region_access_point",
    "resource/aws_s3control_multi_region_access_point_policy",
    "resource/aws_s3control_object_lambda_access_point",
    "resource/aws_s3control_storage_lens_configuration",
    "resource/aws_s3files_access_point",
    "resource/aws_s3files_synchronization_configuration",
    "resource/aws_s3outposts_endpoint",
    "resource/aws_s3tables_namespace",
    "resource/aws_s3tables_table",
    "resource/aws_s3tables_table_bucket",
    "resource/aws_s3tables_table_bucket_replication",
    "resource/aws_s3tables_table_policy",
    "resource/aws_s3tables_table_replication",
    "resource/aws_s3vectors_index",
    "resource/aws_sagemaker_algorithm",
    "resource/aws_sagemaker_app",
    "resource/aws_sagemaker_app_image_config",
    "resource/aws_sagemaker_code_repository",
    "resource/aws_sagemaker_data_quality_job_definition",
    "resource/aws_sagemaker_device",
    "resource/aws_sagemaker_device_fleet",
    "resource/aws_sagemaker_domain",
    "resource/aws_sagemaker_endpoint",
    "resource/aws_sagemaker_endpoint_configuration",
    "resource/aws_sagemaker_feature_group",
    "resource/aws_sagemaker_flow_definition",
    "resource/aws_sagemaker_hub",
    "resource/aws_sagemaker_human_task_ui",
    "resource/aws_sagemaker_hyper_parameter_tuning_job",
    "resource/aws_sagemaker_image_version",
    "resource/aws_sagemaker_labeling_job",
    "resource/aws_sagemaker_model",
    "resource/aws_sagemaker_model_card",
    "resource/aws_sagemaker_model_card_export_job",
    "resource/aws_sagemaker_model_package_group_policy",
    "resource/aws_sagemaker_monitoring_schedule",
    "resource/aws_sagemaker_notebook_instance",
    "resource/aws_sagemaker_pipeline",
    "resource/aws_sagemaker_project",
    "resource/aws_sagemaker_training_job",
    "resource/aws_sagemaker_user_profile",
    "resource/aws_sagemaker_workforce",
    "resource/aws_sagemaker_workteam",
    "resource/aws_savingsplans_savings_plan",
    "resource/aws_scheduler_schedule",
    "resource/aws_secretsmanager_secret",
    "resource/aws_secretsmanager_secret_rotation",
    "resource/aws_secretsmanager_secret_version",
    "resource/aws_security_group_rule",
    "resource/aws_securityhub_automation_rule",
    "resource/aws_securityhub_automation_rule_v2",
    "resource/aws_securityhub_configuration_policy",
    "resource/aws_securityhub_connector_v2",
    "resource/aws_securityhub_insight",
    "resource/aws_securityhub_organization_configuration",
    "resource/aws_securityhub_product_subscription",
    "resource/aws_securityhub_standards_subscription",
    "resource/aws_securitylake_aws_log_source",
    "resource/aws_securitylake_custom_log_source",
    "resource/aws_securitylake_data_lake",
    "resource/aws_securitylake_subscriber",
    "resource/aws_securitylake_subscriber_notification",
    "resource/aws_servicecatalog_constraint",
    "resource/aws_servicecatalog_portfolio",
    "resource/aws_servicecatalog_product",
    "resource/aws_servicecatalog_product_portfolio_association",
    "resource/aws_servicecatalog_provisioned_product",
    "resource/aws_servicecatalog_provisioning_artifact",
    "resource/aws_servicecatalog_service_action",
    "resource/aws_servicecatalog_tag_option",
    "resource/aws_servicequotas_service_quota",
    "resource/aws_ses_configuration_set",
    "resource/aws_ses_domain_dkim",
    "resource/aws_ses_event_destination",
    "resource/aws_ses_receipt_rule",
    "resource/aws_sesv2_account_vdm_attributes",
    "resource/aws_sesv2_configuration_set",
    "resource/aws_sesv2_configuration_set_event_destination",
    "resource/aws_sesv2_contact_list",
    "resource/aws_sesv2_email_identity",
    "resource/aws_sesv2_tenant",
    "resource/aws_sfn_activity",
    "resource/aws_sfn_alias",
    "resource/aws_sfn_state_machine",
    "resource/aws_shield_proactive_engagement",
    "resource/aws_signer_signing_job",
    "resource/aws_sns_platform_application",
    "resource/aws_sns_topic_subscription",
    "resource/aws_spot_fleet_request",
    "resource/aws_spot_instance_request",
    "resource/aws_ssm_association",
    "resource/aws_ssm_default_patch_baseline",
    "resource/aws_ssm_document",
    "resource/aws_ssm_maintenance_window_target",
    "resource/aws_ssm_maintenance_window_task",
    "resource/aws_ssm_patch_baseline",
    "resource/aws_ssm_resource_data_sync",
    "resource/aws_ssmcontacts_contact_channel",
    "resource/aws_ssmcontacts_plan",
    "resource/aws_ssmcontacts_rotation",
    "resource/aws_ssmincidents_replication_set",
    "resource/aws_ssmincidents_response_plan",
    "resource/aws_ssmquicksetup_configuration_manager",
    "resource/aws_ssoadmin_application",
    "resource/aws_ssoadmin_customer_managed_policy_attachment",
    "resource/aws_ssoadmin_customer_managed_policy_attachments_exclusive",
    "resource/aws_ssoadmin_instance_access_control_attributes",
    "resource/aws_ssoadmin_permissions_boundary_attachment",
    "resource/aws_ssoadmin_trusted_token_issuer",
    "resource/aws_storagegateway_file_system_association",
    "resource/aws_storagegateway_gateway",
    "resource/aws_storagegateway_nfs_file_share",
    "resource/aws_storagegateway_smb_file_share",
    "resource/aws_storagegateway_stored_iscsi_volume",
    "resource/aws_subnet",
    "resource/aws_synthetics_canary",
    "resource/aws_synthetics_group_association",
    "resource/aws_timestreaminfluxdb_db_cluster",
    "resource/aws_timestreaminfluxdb_db_instance",
    "resource/aws_timestreamquery_scheduled_query",
    "resource/aws_timestreamwrite_table",
    "resource/aws_transcribe_language_model",
    "resource/aws_transfer_access",
    "resource/aws_transfer_agreement",
    "resource/aws_transfer_connector",
    "resource/aws_transfer_server",
    "resource/aws_transfer_ssh_key",
    "resource/aws_transfer_user",
    "resource/aws_transfer_web_app",
    "resource/aws_transfer_web_app_customization",
    "resource/aws_transfer_workflow",
    "resource/aws_verifiedaccess_endpoint",
    "resource/aws_verifiedaccess_group",
    "resource/aws_verifiedaccess_instance",
    "resource/aws_verifiedaccess_instance_logging_configuration",
    "resource/aws_verifiedaccess_trust_provider",
    "resource/aws_verifiedpermissions_identity_source",
    "resource/aws_verifiedpermissions_policy",
    "resource/aws_verifiedpermissions_policy_store",
    "resource/aws_verifiedpermissions_schema",
    "resource/aws_volume_attachment",
    "resource/aws_vpc",
    "resource/aws_vpc_dhcp_options",
    "resource/aws_vpc_encryption_control",
    "resource/aws_vpc_endpoint",
    "resource/aws_vpc_endpoint_service",
    "resource/aws_vpc_ipam",
    "resource/aws_vpc_ipam_pool",
    "resource/aws_vpc_ipam_pool_cidr",
    "resource/aws_vpc_ipam_pool_cidr_allocation",
    "resource/aws_vpc_ipam_resource_discovery",
    "resource/aws_vpc_ipam_scope",
    "resource/aws_vpc_peering_connection",
    "resource/aws_vpc_peering_connection_accepter",
    "resource/aws_vpc_peering_connection_options",
    "resource/aws_vpc_route_server_peer",
    "resource/aws_vpclattice_access_log_subscription",
    "resource/aws_vpclattice_listener",
    "resource/aws_vpclattice_listener_rule",
    "resource/aws_vpclattice_resource_configuration",
    "resource/aws_vpclattice_resource_gateway",
    "resource/aws_vpclattice_service_network_resource_association",
    "resource/aws_vpclattice_service_network_service_association",
    "resource/aws_vpclattice_service_network_vpc_association",
    "resource/aws_vpclattice_target_group",
    "resource/aws_vpclattice_target_group_attachment",
    "resource/aws_vpn_connection",
    "resource/aws_vpn_gateway_route_propagation",
    "resource/aws_waf_byte_match_set",
    "resource/aws_waf_geo_match_set",
    "resource/aws_waf_ipset",
    "resource/aws_waf_rate_based_rule",
    "resource/aws_waf_regex_match_set",
    "resource/aws_waf_rule",
    "resource/aws_waf_rule_group",
    "resource/aws_waf_size_constraint_set",
    "resource/aws_waf_sql_injection_match_set",
    "resource/aws_waf_web_acl",
    "resource/aws_waf_xss_match_set",
    "resource/aws_wafregional_byte_match_set",
    "resource/aws_wafregional_geo_match_set",
    "resource/aws_wafregional_ipset",
    "resource/aws_wafregional_rate_based_rule",
    "resource/aws_wafregional_regex_match_set",
    "resource/aws_wafregional_rule",
    "resource/aws_wafregional_rule_group",
    "resource/aws_wafregional_size_constraint_set",
    "resource/aws_wafregional_sql_injection_match_set",
    "resource/aws_wafregional_web_acl",
    "resource/aws_wafregional_xss_match_set",
    "resource/aws_wafv2_ip_set",
    "resource/aws_wafv2_regex_pattern_set",
    "resource/aws_wafv2_rule_group",
    "resource/aws_wafv2_web_acl",
    "resource/aws_wafv2_web_acl_logging_configuration",
    "resource/aws_wafv2_web_acl_rule",
    "resource/aws_wafv2_web_acl_rule_group_association",
    "resource/aws_workmail_group",
    "resource/aws_workmail_organization",
    "resource/aws_workspaces_directory",
    "resource/aws_workspaces_ip_group",
    "resource/aws_workspaces_workspace",
    "resource/aws_workspacesweb_data_protection_settings",
    "resource/aws_workspacesweb_identity_provider",
    "resource/aws_workspacesweb_ip_access_settings",
    "resource/aws_workspacesweb_session_logger",
    "resource/aws_workspacesweb_trust_store",
    "resource/aws_workspacesweb_user_settings",
    "resource/aws_xray_group",
  ]
}

check "import_section" {
  enabled = true
  require_identity_section = true

  prefixes = [
    "aws_accessanalyzer",
    "aws_account",
    "aws_alb",
    "aws_ami",
    "aws_amplify",
    "aws_api",
    "aws_apigatewayv2",
    "aws_app",
    "aws_appautoscaling",
    "aws_appconfig",
    "aws_appfabric",
    "aws_appflow",
    "aws_appintegrations",
    "aws_applicationinsights",
    "aws_appmesh",
    "aws_apprunner",
    "aws_appstream",
    "aws_appsync",
    "aws_arczonalshift",
    "aws_arn",
    "aws_athena",
    "aws_autoscaling",
    "aws_autoscalingplans",
    "aws_availability",
    "aws_batch",
    "aws_bcmdataexports",
    "aws_bedrockagent",
    "aws_bedrockagentcore",
    "aws_billing",
    "aws_budgets",
    "aws_caller",
    "aws_canonical",
    "aws_ce",
    "aws_chatbot",
    "aws_chime",
    "aws_chimesdkmediapipelines",
    "aws_chimesdkvoice",
    "aws_cleanrooms",
    "aws_cloud9",
    "aws_cloudcontrolapi",
    "aws_cloudformation",
    "aws_cloudfront",
    "aws_cloudfrontkeyvaluestore",
    "aws_cloudhsm",
    "aws_cloudsearch",
    "aws_codecatalyst",
    "aws_codecommit",
    "aws_codeconnections",
    "aws_codedeploy",
    "aws_codeguruprofiler",
    "aws_codegurureviewer",
    "aws_codepipeline",
    "aws_codestarconnections",
    "aws_codestarnotifications",
    "aws_cognito",
    "aws_comprehend",
    "aws_computeoptimizer",
    "aws_config",
    "aws_connect",
    "aws_controltower",
    "aws_costoptimizationhub",
    "aws_cur",
    "aws_customer",
    "aws_customerprofiles",
    "aws_dataexchange",
    "aws_datapipeline",
    "aws_datasync",
    "aws_datazone",
    "aws_dax",
    "aws_db",
    "aws_default",
    "aws_detective",
    "aws_devicefarm",
    "aws_directory",
    "aws_dlm",
    "aws_dms",
    "aws_docdb",
    "aws_docdbelastic",
    "aws_drs",
    "aws_dsql",
    "aws_ecr",
    "aws_ecrpublic",
    "aws_ecs",
    "aws_efs",
    "aws_egress",
    "aws_eip",
    "aws_eips",
    "aws_eks",
    "aws_elastic",
    "aws_elasticache",
    "aws_elasticsearch",
    "aws_elastictranscoder",
    "aws_elb",
    "aws_emr",
    "aws_emrcontainers",
    "aws_emrserverless",
    "aws_events",
    "aws_evidently",
    "aws_finspace",
    "aws_fis",
    "aws_flow",
    "aws_fms",
    "aws_fsx",
    "aws_gamelift",
    "aws_glacier",
    "aws_globalaccelerator",
    "aws_grafana",
    "aws_guardduty",
    "aws_identitystore",
    "aws_imagebuilder",
    "aws_instance",
    "aws_instances",
    "aws_internet",
    "aws_internetmonitor",
    "aws_ip",
    "aws_ivs",
    "aws_ivschat",
    "aws_kendra",
    "aws_key",
    "aws_keyspaces",
    "aws_kinesisanalyticsv2",
    "aws_kms",
    "aws_launch",
    "aws_lbs",
    "aws_lex",
    "aws_lexv2models",
    "aws_licensemanager",
    "aws_lightsail",
    "aws_load",
    "aws_location",
    "aws_m2",
    "aws_main",
    "aws_media",
    "aws_medialive",
    "aws_memorydb",
    "aws_mq",
    "aws_mskconnect",
    "aws_mwaa",
    "aws_nat",
    "aws_neptune",
    "aws_neptunegraph",
    "aws_network",
    "aws_networkfirewall",
    "aws_networkflowmonitor",
    "aws_networkmanager",
    "aws_networkmonitor",
    "aws_notifications",
    "aws_notificationscontacts",
    "aws_oam",
    "aws_observabilityadmin",
    "aws_odb",
    "aws_opensearch",
    "aws_opensearchserverless",
    "aws_osis",
    "aws_outposts",
    "aws_partition",
    "aws_paymentcryptography",
    "aws_pinpoint",
    "aws_pinpointsmsvoicev2",
    "aws_pipes",
    "aws_placement",
    "aws_polly",
    "aws_prefix",
    "aws_pricing",
    "aws_proxy",
    "aws_qbusiness",
    "aws_qldb",
    "aws_quicksight",
    "aws_rbin",
    "aws_redshiftdata",
    "aws_redshiftserverless",
    "aws_region",
    "aws_regions",
    "aws_rekognition",
    "aws_resiliencehub",
    "aws_resourceexplorer2",
    "aws_resourcegroups",
    "aws_resourcegroupstaggingapi",
    "aws_rolesanywhere",
    "aws_route53domains",
    "aws_route53profiles",
    "aws_route53recoverycontrolconfig",
    "aws_route53recoveryreadiness",
    "aws_rum",
    "aws_s3control",
    "aws_s3files",
    "aws_s3outposts",
    "aws_savingsplans",
    "aws_scheduler",
    "aws_schemas",
    "aws_security",
    "aws_securityhub",
    "aws_securitylake",
    "aws_serverlessapplicationrepository",
    "aws_servicecatalog",
    "aws_servicecatalogappregistry",
    "aws_servicequotas",
    "aws_ses",
    "aws_sesv2",
    "aws_shield",
    "aws_signer",
    "aws_snapshot",
    "aws_sns",
    "aws_spot",
    "aws_ssm",
    "aws_ssmcontacts",
    "aws_ssmincidents",
    "aws_ssmquicksetup",
    "aws_storagegateway",
    "aws_sts",
    "aws_subnet",
    "aws_subnets",
    "aws_swf",
    "aws_synthetics",
    "aws_timestreaminfluxdb",
    "aws_timestreamquery",
    "aws_timestreamwrite",
    "aws_transcribe",
    "aws_transfer",
    "aws_verifiedaccess",
    "aws_vpclattice",
    "aws_vpcs",
    "aws_vpn",
    "aws_wafregional",
    "aws_workspaces",
    "aws_workspacesweb",
  ]
}

check "frontmatter" {
  enabled = true

  require_subcategory = true
  require_page_title  = true
  require_description = true
  require_layout      = true

  allow_subcategories_file = "website/allowed-subcategories.txt"

  allow_empty_subcategory_targets = [
    "arn_build",
    "arn_parse",
    "trim_iam_role_path",
    "user_agent",
  ]
}

check "section_presence" {
  enabled = false
}

check "timeouts_section" {
  enabled = true

  ignore_targets = [
    "aws_autoscaling_group",
    "aws_bedrock_custom_model",
    "aws_bedrockagent_agent_action_group",
    "aws_bedrockagent_agent_knowledge_base_association",
    "aws_budgets_budget_action",
    "aws_dx_hosted_private_virtual_interface",
    "aws_dx_hosted_transit_virtual_interface",
    "aws_eks_access_entry",
    "aws_eks_access_policy_association",
    "aws_fsx_openzfs_snapshot",
    "aws_globalaccelerator_custom_routing_endpoint_group",
    "aws_oam_sink_policy",
    "aws_quicksight_account_subscription",
    "aws_route53profiles_profile",
    "aws_route53profiles_resource_association",
    "aws_s3control_multi_region_access_point",
    "aws_spot_fleet_request",
    "aws_vpclattice_service",
    "aws_vpclattice_service_network_service_association",
    "aws_vpclattice_service_network_vpc_association",
    "aws_vpclattice_target_group",
    "aws_workspaces_connection_alias",
  ]
}

check "region_argument" {
  enabled = true
  ignore_resources = [
    "aws_default_subnet",
    "aws_default_vpc",
    "aws_default_vpc_dhcp_options",
    "aws_kms_secrets",
  ]
}

check "file_check" {
  enabled = true
  max_file_size = 500000
  allow_extensions = [".html.markdown"]
  allow_registry_extensions = [".md"]
  inline_links = true

  ignore_targets = [
    "resource/aws_acm_certificate",
    "resource/aws_appflow_connector_profile",
    "resource/aws_appflow_connector_profile",
    "resource/aws_appmesh_gateway_route",
    "resource/aws_appmesh_route",
    "resource/aws_appmesh_virtual_gateway",
    "resource/aws_appmesh_virtual_node",
    "resource/aws_appmesh_virtual_router",
    "resource/aws_appmesh_virtual_service",
    "resource/aws_autoscaling_notification",
    "resource/aws_autoscaling_notification",
    "resource/aws_batch_compute_environment",
    "resource/aws_batch_compute_environment",
    "resource/aws_batch_compute_environment",
    "resource/aws_bedrockagent_data_source",
    "resource/aws_bedrockagent_data_source",
    "resource/aws_bedrockagent_data_source",
    "resource/aws_bedrockagent_data_source",
    "resource/aws_cloudfront_connection_group",
    "resource/aws_cloudfront_distribution",
    "resource/aws_cloudfront_distribution",
    "resource/aws_cloudfront_distribution",
    "resource/aws_cloudfront_distribution",
    "resource/aws_cloudfront_distribution",
    "resource/aws_cloudfront_distribution",
    "resource/aws_cloudfront_distribution",
    "resource/aws_cloudfront_origin_access_identity",
    "resource/aws_cloudfront_origin_access_identity",
    "resource/aws_cloudfront_origin_access_identity",
    "resource/aws_cloudfront_origin_access_identity",
    "resource/aws_cloudfront_vpc_origin",
    "resource/aws_cloudhsm_v2_cluster",
    "resource/aws_cloudhsm_v2_cluster",
    "resource/aws_codedeploy_deployment_group",
    "resource/aws_dax_cluster",
    "resource/aws_default_network_acl",
    "resource/aws_default_route_table",
    "resource/aws_default_security_group",
    "resource/aws_devicefarm_project",
    "resource/aws_ec2_transit_gateway_peering_attachment",
    "resource/aws_eip",
    "resource/aws_elastic_beanstalk_configuration_template",
    "resource/aws_elastic_beanstalk_environment",
    "resource/aws_elastic_beanstalk_environment",
    "resource/aws_elastic_beanstalk_environment",
    "resource/aws_globalaccelerator_accelerator",
    "resource/aws_globalaccelerator_custom_routing_accelerator",
    "resource/aws_iam_group",
    "resource/aws_iam_group_membership",
    "resource/aws_iam_group_membership",
    "resource/aws_iam_group_membership",
    "resource/aws_iam_instance_profile",
    "resource/aws_iam_server_certificate",
    "resource/aws_iam_server_certificate",
    "resource/aws_iam_server_certificate",
    "resource/aws_iam_user",
    "resource/aws_iam_user_group_membership",
    "resource/aws_iam_user_group_membership",
    "resource/aws_iam_user_group_membership",
    "resource/aws_kinesis_analytics_application",
    "resource/aws_kinesis_firehose_delivery_stream",
    "resource/aws_kinesis_stream",
    "resource/aws_kinesis_stream",
    "resource/aws_kinesis_stream",
    "resource/aws_kinesis_stream_consumer",
    "resource/aws_kinesis_video_stream",
    "resource/aws_kinesis_video_stream",
    "resource/aws_kinesis_video_stream",
    "resource/aws_launch_configuration",
    "resource/aws_launch_configuration",
    "resource/aws_launch_configuration",
    "resource/aws_main_route_table_association",
    "resource/aws_main_route_table_association",
    "resource/aws_main_route_table_association",
    "resource/aws_neptune_cluster_instance",
    "resource/aws_network_interface_sg_attachment",
    "resource/aws_network_interface_sg_attachment",
    "resource/aws_rds_cluster",
    "resource/aws_rds_cluster",
    "resource/aws_rds_cluster",
    "resource/aws_rds_cluster",
    "resource/aws_rds_cluster",
    "resource/aws_rds_cluster_activity_stream",
    "resource/aws_rds_cluster_activity_stream",
    "resource/aws_rds_cluster_activity_stream",
    "resource/aws_rds_cluster_endpoint",
    "resource/aws_rds_cluster_instance",
    "resource/aws_rds_cluster_instance",
    "resource/aws_rds_cluster_instance",
    "resource/aws_rds_cluster_instance",
    "resource/aws_rds_cluster_instance",
    "resource/aws_rds_cluster_instance",
    "resource/aws_s3_bucket_acl",
    "resource/aws_sns_platform_application",
    "resource/aws_sns_platform_application",
    "resource/aws_ssm_document",
    "resource/aws_ssm_document",
    "resource/aws_volume_attachment",
    "resource/aws_volume_attachment",
    "resource/aws_volume_attachment",
    "resource/aws_vpc_peering_connection",
    "resource/aws_wafv2_web_acl_association",
    "resource/aws_wafv2_web_acl_association",
    "data_source/aws_customer_gateway",
    "data_source/aws_ebs_snapshot",
    "data_source/aws_ebs_snapshot_ids",
    "data_source/aws_ebs_volume",
    "data_source/aws_ec2_transit_gateway_attachments",
    "data_source/aws_ec2_transit_gateway_attachments",
    "data_source/aws_ec2_transit_gateway_peering_attachments",
    "data_source/aws_ec2_transit_gateway_peering_attachments",
    "data_source/aws_ec2_transit_gateway_vpc_attachments",
    "data_source/aws_ec2_transit_gateway_vpc_attachments",
    "data_source/aws_elastic_beanstalk_solution_stack",
    "data_source/aws_iam_roles",
    "data_source/aws_iam_users",
    "data_source/aws_instance",
    "data_source/aws_instances",
    "data_source/aws_ip_ranges",
    "data_source/aws_ip_ranges",
    "data_source/aws_kinesis_firehose_delivery_stream",
    "data_source/aws_kinesis_stream",
    "data_source/aws_kinesis_stream",
    "data_source/aws_kinesis_stream",
    "data_source/aws_kinesis_stream",
    "data_source/aws_kinesis_stream_consumer",
    "data_source/aws_networkfirewall_firewall_policy",
    "data_source/aws_networkfirewall_firewall_policy",
    "data_source/aws_networkfirewall_resource_policy",
    "data_source/aws_regions",
    "data_source/aws_route53_resolver_endpoint",
    "data_source/aws_route53_resolver_query_log_config",
    "data_source/aws_security_groups",
    "list_resource/aws_ebs_volume",
    "list_resource/aws_ec2_secondary_subnet",
    "list_resource/aws_instance",
    "list_resource/aws_internet_gateway",
    "list_resource/aws_nat_gateway",
    "list_resource/aws_route_table",
    "list_resource/aws_subnet",
    "list_resource/aws_vpc",
    "list_resource/aws_vpc_endpoint",
  ]
}

check "file_match" {
  enabled = true
  ignore_missing = [
    "aws_alb",
    "aws_alb_listener",
    "aws_alb_listener_certificate",
    "aws_alb_listener_rule",
    "aws_alb_target_group",
    "aws_alb_target_group_attachment",
    "aws_alb_trust_store",
    "aws_alb_trust_store_revocation",
    "aws_albs",
  ]
}
