// Code generated by internal/generate/servicepackage/main.go; DO NOT EDIT.

package meta

import (
	"context"

	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	itypes "github.com/hashicorp/terraform-provider-aws/internal/types"
)

type servicePackage struct{}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*itypes.ServicePackageFrameworkDataSource {
	return []*itypes.ServicePackageFrameworkDataSource{
		{
			Factory:  newARNDataSource,
			TypeName: "aws_arn",
			Name:     "ARN",
		},
		{
			Factory:  newDefaultTagsDataSource,
			TypeName: "aws_default_tags",
			Name:     "Default Tags",
		},
		{
			Factory:  newIPRangesDataSource,
			TypeName: "aws_ip_ranges",
			Name:     "IP Ranges",
		},
		{
			Factory:  newPartitionDataSource,
			TypeName: "aws_partition",
			Name:     "Partition",
		},
		{
			Factory:  newRegionDataSource,
			TypeName: "aws_region",
			Name:     "Region",
		},
		{
			Factory:  newRegionsDataSource,
			TypeName: "aws_regions",
			Name:     "Regions",
		},
		{
			Factory:  newServiceDataSource,
			TypeName: "aws_service",
			Name:     "Service",
		},
		{
			Factory:  newServicePrincipalDataSource,
			TypeName: "aws_service_principal",
			Name:     "Service Principal",
		},
	}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*itypes.ServicePackageFrameworkResource {
	return []*itypes.ServicePackageFrameworkResource{}
}

func (p *servicePackage) SDKDataSources(ctx context.Context) []*itypes.ServicePackageSDKDataSource {
	return []*itypes.ServicePackageSDKDataSource{}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*itypes.ServicePackageSDKResource {
	return []*itypes.ServicePackageSDKResource{}
}

func (p *servicePackage) ServicePackageName() string {
	return "meta"
}

func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
