// Code generated by "internal/generate/listpages/main.go -AWSSDKVersion=2 -ListOps=DescribeDirectories,DescribeRegions"; DO NOT EDIT.

package ds

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/directoryservice"
)

func describeDirectoriesPages(ctx context.Context, conn *directoryservice.Client, input *directoryservice.DescribeDirectoriesInput, fn func(*directoryservice.DescribeDirectoriesOutput, bool) bool) error {
	for {
		output, err := conn.DescribeDirectories(ctx, input)
		if err != nil {
			return err
		}

		lastPage := aws.ToString(output.NextToken) == ""
		if !fn(output, lastPage) || lastPage {
			break
		}

		input.NextToken = output.NextToken
	}
	return nil
}
func describeRegionsPages(ctx context.Context, conn *directoryservice.Client, input *directoryservice.DescribeRegionsInput, fn func(*directoryservice.DescribeRegionsOutput, bool) bool) error {
	for {
		output, err := conn.DescribeRegions(ctx, input)
		if err != nil {
			return err
		}

		lastPage := aws.ToString(output.NextToken) == ""
		if !fn(output, lastPage) || lastPage {
			break
		}

		input.NextToken = output.NextToken
	}
	return nil
}
