// Code generated by internal/generate/servicepackage/main.go; DO NOT EDIT.

package macie2

import (
	"context"

	aws_sdkv1 "github.com/aws/aws-sdk-go/aws"
	session_sdkv1 "github.com/aws/aws-sdk-go/aws/session"
	macie2_sdkv1 "github.com/aws/aws-sdk-go/service/macie2"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*types.ServicePackageFrameworkDataSource {
	return []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
	return []*types.ServicePackageFrameworkResource{}
}

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
			Factory:  ResourceAccount,
			TypeName: "aws_macie2_account",
		},
		{
			Factory:  ResourceClassificationExportConfiguration,
			TypeName: "aws_macie2_classification_export_configuration",
		},
		{
			Factory:  ResourceClassificationJob,
			TypeName: "aws_macie2_classification_job",
			Name:     "Classification Job",
			Tags:     &types.ServicePackageResourceTags{},
		},
		{
			Factory:  ResourceCustomDataIdentifier,
			TypeName: "aws_macie2_custom_data_identifier",
			Name:     "Custom Data Identifier",
			Tags:     &types.ServicePackageResourceTags{},
		},
		{
			Factory:  ResourceFindingsFilter,
			TypeName: "aws_macie2_findings_filter",
			Name:     "Findings Filter",
			Tags:     &types.ServicePackageResourceTags{},
		},
		{
			Factory:  ResourceInvitationAccepter,
			TypeName: "aws_macie2_invitation_accepter",
		},
		{
			Factory:  ResourceMember,
			TypeName: "aws_macie2_member",
			Name:     "Member",
			Tags:     &types.ServicePackageResourceTags{},
		},
		{
			Factory:  ResourceOrganizationAdminAccount,
			TypeName: "aws_macie2_organization_admin_account",
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.Macie2
}

// NewConn returns a new AWS SDK for Go v1 client for this service package's AWS API.
func (p *servicePackage) NewConn(ctx context.Context, config map[string]any) (*macie2_sdkv1.Macie2, error) {
	sess := config[names.AttrSession].(*session_sdkv1.Session)

	cfg := aws_sdkv1.Config{}

	if endpoint := config[names.AttrEndpoint].(string); endpoint != "" {
		tflog.Debug(ctx, "setting endpoint", map[string]any{
			"tf_aws.endpoint": endpoint,
		})
		cfg.Endpoint = aws_sdkv1.String(endpoint)
	} else {
		cfg.EndpointResolver = newEndpointResolverSDKv1(ctx)
	}

	return macie2_sdkv1.New(sess.Copy(&cfg)), nil
}

func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
