// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/generate/servicepackage/main.go; DO NOT EDIT.

package ecr

import (
	"context"
	"iter"
	"slices"
	"unique"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/ecr"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-provider-aws/internal/conns"
	inttypes "github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/internal/vcr"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

func (p *servicePackage) EphemeralResources(ctx context.Context) []*inttypes.ServicePackageEphemeralResource {
	return []*inttypes.ServicePackageEphemeralResource{
		{
			Factory:  newAuthorizationTokenEphemeralResource,
			TypeName: "aws_ecr_authorization_token",
			Name:     "AuthorizationToken",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
	}
}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*inttypes.ServicePackageFrameworkDataSource {
	return []*inttypes.ServicePackageFrameworkDataSource{
		{
			Factory:  newImagesDataSource,
			TypeName: "aws_ecr_images",
			Name:     "Images",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  newLifecyclePolicyDocumentDataSource,
			TypeName: "aws_ecr_lifecycle_policy_document",
			Name:     "Lifecycle Policy Document",
			Region:   unique.Make(inttypes.ResourceRegionDisabled()),
		},
		{
			Factory:  newRepositoriesDataSource,
			TypeName: "aws_ecr_repositories",
			Name:     "Repositories",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
	}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*inttypes.ServicePackageFrameworkResource {
	return []*inttypes.ServicePackageFrameworkResource{
		{
			Factory:  newAccountSettingResource,
			TypeName: "aws_ecr_account_setting",
			Name:     "Account Setting",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  newPullTimeUpdateExclusionResource,
			TypeName: "aws_ecr_pull_time_update_exclusion",
			Name:     "Pull Time Update Exclusion",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
	}
}

func (p *servicePackage) SDKDataSources(ctx context.Context) []*inttypes.ServicePackageSDKDataSource {
	return []*inttypes.ServicePackageSDKDataSource{
		{
			Factory:  dataSourceAuthorizationToken,
			TypeName: "aws_ecr_authorization_token",
			Name:     "Authorization Token",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  dataSourceImage,
			TypeName: "aws_ecr_image",
			Name:     "Image",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  dataSourcePullThroughCacheRule,
			TypeName: "aws_ecr_pull_through_cache_rule",
			Name:     "Pull Through Cache Rule",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  dataSourceRepository,
			TypeName: "aws_ecr_repository",
			Name:     "Repository",
			Tags: unique.Make(inttypes.ServicePackageResourceTags{
				IdentifierAttribute: names.AttrARN,
			}),
			Region: unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  dataSourceRepositoryCreationTemplate,
			TypeName: "aws_ecr_repository_creation_template",
			Name:     "Repository Creation Template",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
	}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*inttypes.ServicePackageSDKResource {
	return []*inttypes.ServicePackageSDKResource{
		{
			Factory:  resourceLifecyclePolicy,
			TypeName: "aws_ecr_lifecycle_policy",
			Name:     "Lifecycle Policy",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
			Identity: inttypes.RegionalSingleParameterIdentity("repository"),
			Import: inttypes.SDKv2Import{
				WrappedImport: true,
			},
		},
		{
			Factory:  resourcePullThroughCacheRule,
			TypeName: "aws_ecr_pull_through_cache_rule",
			Name:     "Pull Through Cache Rule",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  resourceRegistryPolicy,
			TypeName: "aws_ecr_registry_policy",
			Name:     "Registry Policy",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  resourceRegistryScanningConfiguration,
			TypeName: "aws_ecr_registry_scanning_configuration",
			Name:     "Registry Scanning Configuration",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  resourceReplicationConfiguration,
			TypeName: "aws_ecr_replication_configuration",
			Name:     "Replication Configuration",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  resourceRepository,
			TypeName: "aws_ecr_repository",
			Name:     "Repository",
			Tags: unique.Make(inttypes.ServicePackageResourceTags{
				IdentifierAttribute: names.AttrARN,
			}),
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
			Identity: inttypes.RegionalSingleParameterIdentity(names.AttrName),
			Import: inttypes.SDKv2Import{
				WrappedImport: true,
			},
		},
		{
			Factory:  resourceRepositoryCreationTemplate,
			TypeName: "aws_ecr_repository_creation_template",
			Name:     "Repository Creation Template",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
		},
		{
			Factory:  resourceRepositoryPolicy,
			TypeName: "aws_ecr_repository_policy",
			Name:     "Repository Policy",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
			Identity: inttypes.RegionalSingleParameterIdentity("repository"),
			Import: inttypes.SDKv2Import{
				WrappedImport: true,
			},
		},
	}
}

func (p *servicePackage) SDKListResources(ctx context.Context) iter.Seq[*inttypes.ServicePackageSDKListResource] {
	return slices.Values([]*inttypes.ServicePackageSDKListResource{
		{
			Factory:  repositoryResourceAsListResource,
			TypeName: "aws_ecr_repository",
			Name:     "Repository",
			Region:   unique.Make(inttypes.ResourceRegionDefault()),
			Tags: unique.Make(inttypes.ServicePackageResourceTags{
				IdentifierAttribute: names.AttrARN,
			}),
			Identity: inttypes.RegionalSingleParameterIdentity(names.AttrName),
		},
	})
}

func (p *servicePackage) ServicePackageName() string {
	return names.ECR
}

// NewClient returns a new AWS SDK for Go v2 client for this service package's AWS API.
func (p *servicePackage) NewClient(ctx context.Context, config map[string]any) (*ecr.Client, error) {
	cfg := *(config["aws_sdkv2_config"].(*aws.Config))
	optFns := []func(*ecr.Options){
		ecr.WithEndpointResolverV2(newEndpointResolverV2()),
		withBaseEndpoint(config[names.AttrEndpoint].(string)),
		func(o *ecr.Options) {
			if region := config[names.AttrRegion].(string); o.Region != region {
				tflog.Info(ctx, "overriding provider-configured AWS API region", map[string]any{
					"service":         p.ServicePackageName(),
					"original_region": o.Region,
					"override_region": region,
				})
				o.Region = region
			}
		},
		func(o *ecr.Options) {
			if inContext, ok := conns.FromContext(ctx); ok && inContext.VCREnabled() {
				tflog.Info(ctx, "overriding retry behavior to immediately return VCR errors")
				o.Retryer = conns.AddIsErrorRetryables(cfg.Retryer().(aws.RetryerV2), vcr.InteractionNotFoundRetryableFunc)
			}
		},
		withExtraOptions(ctx, p, config),
	}

	return ecr.NewFromConfig(cfg, optFns...), nil
}

// withExtraOptions returns a functional option that allows this service package to specify extra API client options.
// This option is always called after any generated options.
func withExtraOptions(ctx context.Context, sp conns.ServicePackage, config map[string]any) func(*ecr.Options) {
	if v, ok := sp.(interface {
		withExtraOptions(context.Context, map[string]any) []func(*ecr.Options)
	}); ok {
		optFns := v.withExtraOptions(ctx, config)

		return func(o *ecr.Options) {
			for _, optFn := range optFns {
				optFn(o)
			}
		}
	}

	return func(*ecr.Options) {}
}

func ServicePackage(ctx context.Context) conns.ServicePackage {
	return &servicePackage{}
}
