// Code generated by internal/generate/servicepackages/main.go; DO NOT EDIT.

package datasync

import (
	"context"

	"github.com/hashicorp/terraform-provider-aws/internal/types"
	"github.com/hashicorp/terraform-provider-aws/names"
)

type servicePackage struct{}

func (p *servicePackage) FrameworkDataSources(ctx context.Context) []*types.ServicePackageFrameworkDataSource {
	return []*types.ServicePackageFrameworkDataSource{}
}

func (p *servicePackage) FrameworkResources(ctx context.Context) []*types.ServicePackageFrameworkResource {
	return []*types.ServicePackageFrameworkResource{}
}

func (p *servicePackage) SDKDataSources(ctx context.Context) []*types.ServicePackageSDKDataSource {
	return []*types.ServicePackageSDKDataSource{}
}

func (p *servicePackage) SDKResources(ctx context.Context) []*types.ServicePackageSDKResource {
	return []*types.ServicePackageSDKResource{
		{
			Factory:  ResourceAgent,
			TypeName: "aws_datasync_agent",
		},
		{
			Factory:  ResourceLocationEFS,
			TypeName: "aws_datasync_location_efs",
		},
		{
			Factory:  ResourceLocationFSxLustreFileSystem,
			TypeName: "aws_datasync_location_fsx_lustre_file_system",
		},
		{
			Factory:  ResourceLocationFSxOpenZFSFileSystem,
			TypeName: "aws_datasync_location_fsx_openzfs_file_system",
		},
		{
			Factory:  ResourceLocationFSxWindowsFileSystem,
			TypeName: "aws_datasync_location_fsx_windows_file_system",
		},
		{
			Factory:  ResourceLocationHDFS,
			TypeName: "aws_datasync_location_hdfs",
		},
		{
			Factory:  ResourceLocationNFS,
			TypeName: "aws_datasync_location_nfs",
		},
		{
			Factory:  ResourceLocationObjectStorage,
			TypeName: "aws_datasync_location_object_storage",
		},
		{
			Factory:  ResourceLocationS3,
			TypeName: "aws_datasync_location_s3",
		},
		{
			Factory:  ResourceLocationSMB,
			TypeName: "aws_datasync_location_smb",
		},
		{
			Factory:  ResourceTask,
			TypeName: "aws_datasync_task",
		},
	}
}

func (p *servicePackage) ServicePackageName() string {
	return names.DataSync
}

var ServicePackage = &servicePackage{}
