// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package names

const (
	AttrARN                        = "arn"
	AttrAccountID                  = "account_id"
	AttrAutoMinorVersionUpgrade    = "auto_minor_version_upgrade"
	AttrAvailabilityZone           = "availability_zone"
	AttrAvailabilityZones          = "availability_zones"
	AttrBucket                     = "bucket"
	AttrBucketName                 = "bucket_name"
	AttrClusterIdentifier          = "cluster_identifier"
	AttrCreatedAt                  = "created_at"
	AttrCreatedDate                = "created_date"
	AttrDatabaseName               = "database_name"
	AttrDeleteOnTermination        = "delete_on_termination"
	AttrDescription                = "description"
	AttrDomainName                 = "domain_name"
	AttrEnabled                    = "enabled"
	AttrEngineVersion              = "engine_version"
	AttrID                         = "id" // Should be explicitly declared only for Framework resources
	AttrInstanceID                 = "instance_id"
	AttrInstanceType               = "instance_type"
	AttrKMSKeyARN                  = "kms_key_arn"
	AttrKMSKeyID                   = "kms_key_id"
	AttrKey                        = "key"
	AttrLastUpdatedDate            = "last_updated_date"
	AttrMax                        = "max"
	AttrMin                        = "min"
	AttrName                       = "name"
	AttrNamePrefix                 = "name_prefix"
	AttrNetworkInterfaceID         = "network_interface_id"
	AttrOwnerID                    = "owner_id"
	AttrParameters                 = "parameters"
	AttrPolicy                     = "policy"
	AttrPort                       = "port"
	AttrPreferredMaintenanceWindow = "preferred_maintenance_window"
	AttrProtocol                   = "protocol"
	AttrResourceARN                = "resource_arn"
	AttrRoleARN                    = "role_arn"
	AttrSecurityGroupIDs           = "security_group_ids"
	AttrSecurityGroups             = "security_groups"
	AttrState                      = "state"
	AttrStatus                     = "status"
	AttrSubnetID                   = "subnet_id"
	AttrSubnetIDs                  = "subnet_ids"
	AttrTags                       = "tags"
	AttrTagsAll                    = "tags_all"
	AttrTimeouts                   = "timeouts" // Should be explicitly declared only for Framework resources
	AttrTransitGatewayAttachmentID = "transit_gateway_attachment_id"
	AttrTransitGatewayID           = "transit_gateway_id"
	AttrType                       = "type"
	AttrVPCSecurityGroupIDs        = "vpc_security_group_ids"
	AttrValue                      = "value"
	AttrVersion                    = "version"
	AttrVPCID                      = "vpc_id"
)
