// Code generated by "aws/internal/generators/listpages/main.go -function=ListEventBuses,ListRules,ListTargetsByRule github.com/aws/aws-sdk-go/service/cloudwatchevents"; DO NOT EDIT.

package cloudwatchevents

import (
	"context"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/cloudwatchevents"
)

func ListEventBusesPages(conn *cloudwatchevents.CloudWatchEvents, input *cloudwatchevents.ListEventBusesInput, fn func(*cloudwatchevents.ListEventBusesOutput, bool) bool) error {
	return ListEventBusesPagesWithContext(context.Background(), conn, input, fn)
}

func ListEventBusesPagesWithContext(ctx context.Context, conn *cloudwatchevents.CloudWatchEvents, input *cloudwatchevents.ListEventBusesInput, fn func(*cloudwatchevents.ListEventBusesOutput, bool) bool) error {
	for {
		output, err := conn.ListEventBusesWithContext(ctx, input)
		if err != nil {
			return err
		}

		lastPage := aws.StringValue(output.NextToken) == ""
		if !fn(output, lastPage) || lastPage {
			break
		}

		input.NextToken = output.NextToken
	}
	return nil
}

func ListRulesPages(conn *cloudwatchevents.CloudWatchEvents, input *cloudwatchevents.ListRulesInput, fn func(*cloudwatchevents.ListRulesOutput, bool) bool) error {
	return ListRulesPagesWithContext(context.Background(), conn, input, fn)
}

func ListRulesPagesWithContext(ctx context.Context, conn *cloudwatchevents.CloudWatchEvents, input *cloudwatchevents.ListRulesInput, fn func(*cloudwatchevents.ListRulesOutput, bool) bool) error {
	for {
		output, err := conn.ListRulesWithContext(ctx, input)
		if err != nil {
			return err
		}

		lastPage := aws.StringValue(output.NextToken) == ""
		if !fn(output, lastPage) || lastPage {
			break
		}

		input.NextToken = output.NextToken
	}
	return nil
}

func ListTargetsByRulePages(conn *cloudwatchevents.CloudWatchEvents, input *cloudwatchevents.ListTargetsByRuleInput, fn func(*cloudwatchevents.ListTargetsByRuleOutput, bool) bool) error {
	return ListTargetsByRulePagesWithContext(context.Background(), conn, input, fn)
}

func ListTargetsByRulePagesWithContext(ctx context.Context, conn *cloudwatchevents.CloudWatchEvents, input *cloudwatchevents.ListTargetsByRuleInput, fn func(*cloudwatchevents.ListTargetsByRuleOutput, bool) bool) error {
	for {
		output, err := conn.ListTargetsByRuleWithContext(ctx, input)
		if err != nil {
			return err
		}

		lastPage := aws.StringValue(output.NextToken) == ""
		if !fn(output, lastPage) || lastPage {
			break
		}

		input.NextToken = output.NextToken
	}
	return nil
}
