# Copyright IBM Corp. 2014, 2026
# "SPDX-License-Identifier: MPL-2.0"

name: Acceptance Test Directory Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/acctest-terraform-lint.yml
      - .ci/.tflint.hcl
      - .ci/opa-policies/**
      - .ci/tools/go.mod
      - go.sum
      - 'internal/service/**/*.tf'

## NOTE: !!!
## When changing these workflows, ensure that the following is updated:
##   - Documentation: docs/continuous-integration.md
##   - Documentation: docs/makefile-cheat-sheet.md
##   - Makefile: ./GNUmakefile

permissions:
  contents: read # required for checkout

jobs:
  tflint-opa-policy-tests:
    uses: ./.github/workflows/tflint-opa-policy-tests.yml

  terrafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e

      - run: terraform fmt -recursive -check

  tflint:
    name: Validate Acceptance Test Terraform
    needs: tflint-opa-policy-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache plugin dir
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci/.tflint.hcl') }}

      - run: cd .ci/tools && go install github.com/terraform-linters/tflint

      - run: tflint --config .ci/.tflint.hcl --init

      - run: |
          # tflint always resolves config flies relative to the working directory when using --recursive
          TFLINT_CONFIG="$(pwd -P)/.ci/.tflint.hcl"
          tflint --config  "${TFLINT_CONFIG}" --chdir=./internal/service --recursive
        env:
          TFLINT_OPA_POLICY_DIR: ${{ github.workspace }}/.ci/opa-policies
