# Copyright IBM Corp. 2014, 2026
# "SPDX-License-Identifier: MPL-2.0"

name: OPA Policy Tests

on:
  workflow_call:

permissions:
  contents: read # required for checkout

jobs:
  opa-tests:
    name: OPA Policy Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache plugin dir
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci/.tflint.hcl') }}

      - run: cd .ci/tools && go install github.com/terraform-linters/tflint
      - run: tflint --config .ci/.tflint.hcl --init
      - run: .ci/opa-policies/tests/run_tests.sh
        env:
          TFLINT_OPA_POLICY_DIR: ${{ github.workspace }}/.ci/opa-policies
